// @vitest-environment happy-dom
import { act } from "react";
import { createRoot } from "react-dom/client";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import type { Stage, Task, Workflow } from "@/shared/types/workflow";

const api = vi.hoisted(() => ({
  listWorkflows: vi.fn(),
  listTasks: vi.fn(),
  listRuns: vi.fn(),
  createTask: vi.fn(),
}));
const dialogs = vi.hoisted(() => ({
  showMessage: vi.fn(),
  showConfirm: vi.fn(),
  showPrompt: vi.fn(),
}));
vi.mock("../../lib/workflow-api", () => ({ workflowApi: api, subscribeWorkflowEvents: vi.fn() }));
vi.mock("@/stores/dialog-store", () => dialogs);
const invoke = vi.hoisted(() => vi.fn());
vi.mock("@tauri-apps/api/core", () => ({ invoke }));

import i18n from "@/shared/i18n";
import { useWorkflowStore } from "../../workflow-store";
import { CreateTaskDialog } from "../CreateTaskDialog";

(globalThis as typeof globalThis & { IS_REACT_ACT_ENVIRONMENT?: boolean }).IS_REACT_ACT_ENVIRONMENT = true;

const ROOT = "C:\\proj";

function stage(role: Stage["role"]): Stage {
  return {
    id: role,
    role,
    name: role,
    prompt: "",
    completionCriteria: "",
    provider: "codex",
    model: null,
    requiresApproval: false,
    timeoutMinutes: 60,
  };
}

function workflow(id: string, patch: Partial<Workflow> = {}): Workflow {
  return {
    id,
    name: `Flow ${id}`,
    enabled: true,
    archived: false,
    stages: [stage("design"), stage("implement"), stage("review")],
    reviewReturnTo: "design",
    maxReentryCount: 5,
    maxConcurrentRuns: 1,
    designDocPath: null,
    issueTracking: "off",
    ...patch,
  };
}

function task(id: string): Task {
  return {
    meta: {
      schemaVersion: 1,
      id,
      title: "t",
      status: "inbox",
      rootId: id,
      parentId: null,
      workflowId: "wf1",
      stageId: "design",
      role: "design",
      autoGenerated: false,
      archived: false,
      createdAt: "2026-09-26T00:00:00Z",
      updatedAt: "2026-09-26T00:00:00Z",
      attention: null,
      history: [],
      awaiting: null,
      planApproved: false,
      userInput: null,
      screeningAck: null,
    },
    body: "",
  };
}

const initialStore = useWorkflowStore.getState();

function setValue(el: HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement, value: string) {
  const setter = Object.getOwnPropertyDescriptor(Object.getPrototypeOf(el), "value")!.set!;
  setter.call(el, value);
  el.dispatchEvent(new Event(el instanceof HTMLSelectElement ? "change" : "input", { bubbles: true }));
}

describe("CreateTaskDialog", () => {
  let root: ReturnType<typeof createRoot>;
  let container: HTMLDivElement;
  let onClose: ReturnType<typeof vi.fn<() => void>>;
  let onAddStandard: ReturnType<typeof vi.fn<() => void>>;

  function setWorkflows(workflows: Workflow[]) {
    useWorkflowStore.setState({
      activeRoot: ROOT,
      projects: {
        [ROOT]: {
          root: ROOT,
          workflows,
          workflowWarnings: [],
          tasks: [],
          taskWarnings: [],
          runs: [],
          progress: {},
          loading: false,
          refreshing: false,
          loaded: true,
          error: null,
        },
      },
    });
    api.listWorkflows.mockResolvedValue({ workflows, warnings: [] });
  }

  beforeEach(async () => {
    await i18n.changeLanguage("en");
    vi.clearAllMocks();
    useWorkflowStore.setState(initialStore, true);
    setWorkflows([
      workflow("wf1"),
      workflow("wf2", { enabled: false }),
      workflow("wf3", { archived: true }),
      workflow("wf4"),
    ]);
    api.listTasks.mockResolvedValue({ tasks: [], warnings: [] });
    api.listRuns.mockResolvedValue({ runs: [], warnings: [] });
    api.createTask.mockResolvedValue(task("t-new"));
    onClose = vi.fn<() => void>();
    onAddStandard = vi.fn<() => void>();
    container = document.createElement("div");
    document.body.appendChild(container);
    root = createRoot(container);
  });

  afterEach(async () => {
    await act(async () => root.unmount());
    container.remove();
  });

  async function render() {
    await act(async () => root.render(<CreateTaskDialog onClose={onClose} onAddStandard={onAddStandard} />));
  }

  function field<T extends HTMLElement = HTMLInputElement>(name: string) {
    return container.querySelector<T>(`[name="${name}"]`);
  }

  function button(label: string) {
    return [...container.querySelectorAll<HTMLButtonElement>("button")].find((b) => b.textContent === label);
  }

  it("lists only enabled, non-archived workflows", async () => {
    await render();
    const select = field<HTMLSelectElement>("workflow")!;
    expect([...select.options].map((o) => o.value)).toEqual(["wf1", "wf4"]);
    expect(select.value).toBe("wf1");
  });

  it("requires a title", async () => {
    await render();
    const create = button(i18n.t("workflow:create.create"))!;
    expect(create.disabled).toBe(true);
    await act(async () => setValue(field("title")!, "   "));
    expect(create.disabled).toBe(true);
    await act(async () => setValue(field("title")!, "Add login"));
    expect(create.disabled).toBe(false);
  });

  it("creates the task, closes and opens its detail", async () => {
    await render();
    await act(async () => setValue(field("title")!, "  Add login  "));
    await act(async () => setValue(field<HTMLTextAreaElement>("body")!, "## Goal"));
    await act(async () => setValue(field<HTMLSelectElement>("workflow")!, "wf4"));
    await act(async () => button(i18n.t("workflow:create.create"))!.click());
    expect(api.createTask).toHaveBeenCalledWith(ROOT, "Add login", "## Goal", "wf4");
    expect(onClose).toHaveBeenCalled();
    expect(useWorkflowStore.getState().selectedTaskId).toBe("t-new");
  });

  it("stays open when creating fails", async () => {
    api.createTask.mockRejectedValue({ code: "WORKFLOW_NOT_FOUND", message: "" });
    await render();
    await act(async () => setValue(field("title")!, "Add login"));
    await act(async () => button(i18n.t("workflow:create.create"))!.click());
    expect(dialogs.showMessage).toHaveBeenCalled();
    expect(onClose).not.toHaveBeenCalled();
    expect(useWorkflowStore.getState().selectedTaskId).toBeNull();
  });

  it("previews the body as sanitized Markdown", async () => {
    await render();
    await act(async () => setValue(field<HTMLTextAreaElement>("body")!, "**bold** <img src=x onerror=alert(1)>"));
    await act(async () => button(i18n.t("workflow:create.preview"))!.click());
    const preview = container.querySelector(".workflow-create__preview")!;
    expect(preview.querySelector("strong")?.textContent).toBe("bold");
    expect(preview.innerHTML).not.toContain("onerror");
    expect(field("body")).toBeNull();
    await act(async () => button(i18n.t("workflow:create.write"))!.click());
    expect(field<HTMLTextAreaElement>("body")!.value).toContain("**bold**");
  });

  it("opens preview links externally instead of navigating", async () => {
    invoke.mockResolvedValue(undefined);
    await render();
    await act(async () => setValue(field<HTMLTextAreaElement>("body")!, "[site](https://example.com/) [rel](a.md)"));
    await act(async () => button(i18n.t("workflow:create.preview"))!.click());
    const links = container.querySelectorAll<HTMLAnchorElement>(".workflow-create__preview a");
    const clicks = [...links].map((a) => {
      const event = new MouseEvent("click", { bubbles: true, cancelable: true });
      a.dispatchEvent(event);
      return event.defaultPrevented;
    });
    expect(clicks).toEqual([true, true]);
    expect(invoke).toHaveBeenCalledTimes(1);
    expect(invoke).toHaveBeenCalledWith("open_external_url", { url: "https://example.com/" });
  });

  it("offers to add the standard workflow when no workflow is usable", async () => {
    setWorkflows([workflow("wf2", { enabled: false })]);
    await render();
    expect(field("workflow")).toBeNull();
    expect(container.textContent).toContain(i18n.t("workflow:create.noWorkflows"));
    expect(button(i18n.t("workflow:create.create"))!.disabled).toBe(true);
    await act(async () => button(i18n.t("workflow:panel.addStandard"))!.click());
    expect(onAddStandard).toHaveBeenCalled();
  });

  it("asks before discarding a typed task and closes from the overlay only on a full press", async () => {
    await render();
    const overlay = container.querySelector<HTMLElement>(".workflow-create-overlay")!;
    const dialog = container.querySelector<HTMLElement>('[role="dialog"]')!;
    await act(async () => {
      dialog.dispatchEvent(new MouseEvent("mousedown", { bubbles: true }));
      overlay.dispatchEvent(new MouseEvent("click", { bubbles: true }));
    });
    expect(onClose).not.toHaveBeenCalled();

    await act(async () => setValue(field("title")!, "Draft"));
    dialogs.showConfirm.mockResolvedValueOnce(false);
    await act(async () =>
      dialog.dispatchEvent(new KeyboardEvent("keydown", { key: "Escape", bubbles: true })),
    );
    expect(dialogs.showConfirm).toHaveBeenCalledWith(
      i18n.t("workflow:create.discardConfirm"),
      expect.objectContaining({ kind: "warning" }),
    );
    expect(onClose).not.toHaveBeenCalled();

    dialogs.showConfirm.mockResolvedValueOnce(true);
    await act(async () => {
      overlay.dispatchEvent(new MouseEvent("mousedown", { bubbles: true }));
      overlay.dispatchEvent(new MouseEvent("click", { bubbles: true }));
    });
    expect(onClose).toHaveBeenCalledTimes(1);
  });
});
