// @vitest-environment happy-dom
import { act } from "react";
import { createRoot } from "react-dom/client";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import type { AttentionReason, Task, TaskMeta } from "@/shared/types/workflow";

vi.mock("../../lib/workflow-api", () => ({
  workflowApi: {
    listWorkflows: vi.fn(),
    listTasks: vi.fn(),
    listRuns: vi.fn(),
    cancelTask: vi.fn(),
    holdTask: vi.fn(),
    resumeTask: vi.fn(),
    markComplete: vi.fn(),
    approvePlan: vi.fn(),
    archiveTask: vi.fn(),
    deleteTask: vi.fn(),
    retryTask: vi.fn(),
    requestRevision: vi.fn(),
    answerQuestion: vi.fn(),
  },
  subscribeWorkflowEvents: vi.fn(),
}));
vi.mock("@/stores/dialog-store", () => ({ showMessage: vi.fn(), showConfirm: vi.fn(), showPrompt: vi.fn() }));

import i18n from "@/shared/i18n";
import { showConfirm, showMessage } from "@/stores/dialog-store";
import { formatCommandError } from "../../lib/format";
import { workflowApi } from "../../lib/workflow-api";
import { useWorkflowStore } from "../../workflow-store";
import { TaskActions } from "../TaskActions";

(globalThis as typeof globalThis & { IS_REACT_ACT_ENVIRONMENT?: boolean }).IS_REACT_ACT_ENVIRONMENT = true;

const ROOT = "C:\\work\\app";
const api = vi.mocked(workflowApi);

function task(patch: Partial<TaskMeta> = {}): Task {
  return {
    meta: {
      schemaVersion: 1,
      id: "t1",
      title: "Task t1",
      status: "inbox",
      rootId: "t1",
      parentId: null,
      workflowId: "wf1",
      stageId: null,
      role: "design",
      autoGenerated: false,
      archived: false,
      createdAt: "2026-09-01T00:00:00Z",
      updatedAt: "2026-09-01T00:00:00Z",
      attention: null,
      history: [],
      awaiting: null,
      planApproved: false,
      userInput: null,
      screeningAck: null,
      ...patch,
    },
    body: "",
  };
}

const initialStore = useWorkflowStore.getState();

describe("TaskActions", () => {
  let root: ReturnType<typeof createRoot>;
  let container: HTMLDivElement;

  beforeEach(async () => {
    await i18n.changeLanguage("en");
    vi.clearAllMocks();
    useWorkflowStore.setState(initialStore, true);
    useWorkflowStore.setState({ activeRoot: ROOT, selectedTaskId: "t1" });
    api.listWorkflows.mockResolvedValue({ workflows: [], warnings: [] });
    api.listTasks.mockResolvedValue({ tasks: [], warnings: [] });
    api.listRuns.mockResolvedValue({ runs: [], warnings: [] });
    for (const fn of [
      api.cancelTask,
      api.holdTask,
      api.resumeTask,
      api.markComplete,
      api.approvePlan,
      api.archiveTask,
      api.retryTask,
      api.requestRevision,
      api.answerQuestion,
    ]) {
      fn.mockResolvedValue(task());
    }
    api.deleteTask.mockResolvedValue(undefined);
    vi.mocked(showConfirm).mockResolvedValue(true);
    container = document.createElement("div");
    document.body.appendChild(container);
    root = createRoot(container);
  });

  afterEach(async () => {
    await act(async () => root.unmount());
    container.remove();
  });

  async function render(t: Task) {
    await act(async () => root.render(<TaskActions task={t} />));
  }

  function buttons(): string[] {
    return [...container.querySelectorAll<HTMLButtonElement>(".workflow-actions__buttons button")].map(
      (b) => b.dataset.action!,
    );
  }

  function button(action: string) {
    return container.querySelector<HTMLButtonElement>(`button[data-action="${action}"]`)!;
  }

  async function click(el: HTMLElement) {
    await act(async () => el.click());
  }

  async function type(el: HTMLTextAreaElement | null, value: string) {
    const setter = Object.getOwnPropertyDescriptor(HTMLTextAreaElement.prototype, "value")!.set!;
    await act(async () => {
      setter.call(el, value);
      el!.dispatchEvent(new Event("input", { bubbles: true }));
    });
  }

  it.each([
    [{ status: "inbox" }, ["cancel"]],
    [{ status: "running" }, ["hold", "cancel"]],
    [{ status: "on_hold" }, ["resume", "cancel"]],
    [{ status: "attention", attention: { code: "ATTENTION_TIMEOUT", params: {} } }, ["retry", "markComplete", "cancel"]],
    [{ status: "awaiting_user", awaiting: { kind: "plan_approval", question: null } }, ["approve", "requestRevision", "cancel"]],
    [{ status: "awaiting_user", awaiting: { kind: "question", question: "?" } }, ["answer", "cancel"]],
    [{ status: "completed" }, ["archive", "delete"]],
    [{ status: "cancelled" }, ["archive", "delete"]],
    [{ status: "completed", archived: true }, ["delete"]],
  ] as [Partial<TaskMeta>, string[]][])("shows the buttons of %j", async (patch, expected) => {
    await render(task(patch));
    expect(buttons()).toEqual(expected);
    for (const action of expected) expect(button(action).textContent).not.toBe("");
  });

  it("runs the simple actions through the store", async () => {
    await render(task({ status: "running" }));
    await click(button("hold"));
    expect(api.holdTask).toHaveBeenCalledWith(ROOT, "t1");
    expect(api.listTasks).toHaveBeenCalled();

    await render(task({ status: "on_hold" }));
    await click(button("resume"));
    expect(api.resumeTask).toHaveBeenCalledWith(ROOT, "t1");
    await click(button("cancel"));
    expect(api.cancelTask).toHaveBeenCalledWith(ROOT, "t1");

    await render(task({ status: "completed" }));
    await click(button("archive"));
    expect(api.archiveTask).toHaveBeenCalledWith(ROOT, "t1");
  });

  it("refreshes silently when hold races with the task finishing", async () => {
    api.holdTask.mockRejectedValue({ code: "TRANSITION_CONFLICT", message: "completed" });
    await render(task({ status: "running" }));
    await click(button("hold"));
    expect(showMessage).not.toHaveBeenCalled();
    expect(api.listTasks).toHaveBeenCalled();
  });

  it("confirms mark complete", async () => {
    await render(task({ status: "attention", attention: { code: "ATTENTION_TIMEOUT", params: {} } }));
    vi.mocked(showConfirm).mockResolvedValueOnce(false);
    await click(button("markComplete"));
    expect(api.markComplete).not.toHaveBeenCalled();
    await click(button("markComplete"));
    expect(api.markComplete).toHaveBeenCalledWith(ROOT, "t1");
  });

  it("approves the plan and requests a revision with the text", async () => {
    await render(task({ status: "awaiting_user", awaiting: { kind: "plan_approval", question: null } }));
    await click(button("approve"));
    expect(api.approvePlan).toHaveBeenCalledWith(ROOT, "t1");

    const textarea = container.querySelector("textarea");
    expect(button("requestRevision").disabled).toBe(true);
    await type(textarea, "   ");
    expect(button("requestRevision").disabled).toBe(true);
    await type(textarea, "Split the migration");
    await click(button("requestRevision"));
    expect(api.requestRevision).toHaveBeenCalledWith(ROOT, "t1", "Split the migration");
  });

  it("answers the question with the text", async () => {
    await render(task({ status: "awaiting_user", awaiting: { kind: "question", question: "Which DB?" } }));
    expect(button("answer").disabled).toBe(true);
    await type(container.querySelector("textarea"), "Postgres");
    await click(button("answer"));
    expect(api.answerQuestion).toHaveBeenCalledWith(ROOT, "t1", "Postgres");
  });

  it("confirms delete, closes the modal on success and shows delete errors", async () => {
    await render(task({ status: "completed" }));
    api.deleteTask.mockRejectedValueOnce({ code: "WORKFLOW_RUN_IN_PROGRESS", message: "" });
    await click(button("delete"));
    expect(showConfirm).toHaveBeenCalled();
    expect(showMessage).toHaveBeenCalledWith(
      formatCommandError({ code: "WORKFLOW_RUN_IN_PROGRESS", message: "" }),
      expect.objectContaining({ kind: "error" }),
    );
    expect(useWorkflowStore.getState().selectedTaskId).toBe("t1");

    await click(button("delete"));
    expect(api.deleteTask).toHaveBeenLastCalledWith(ROOT, "t1");
    expect(useWorkflowStore.getState().selectedTaskId).toBeNull();
  });

  describe("retry dialog", () => {
    function checkboxes(): string[] {
      return [...container.querySelectorAll<HTMLInputElement>('.workflow-retry input[type="checkbox"]')].map((c) => c.name);
    }

    async function openRetry(reason: AttentionReason) {
      await render(task({ status: "attention", attention: reason }));
      await click(button("retry"));
      expect(container.querySelector('.workflow-retry[role="dialog"]')).not.toBeNull();
    }

    function confirmButton() {
      return container.querySelector<HTMLButtonElement>(".workflow-retry__confirm")!;
    }

    it.each([
      [{ code: "ATTENTION_TIMEOUT", params: {} }, []],
      [{ code: "ATTENTION_SCREENING_FLAGGED", params: {} }, ["acceptScreening"]],
      [{ code: "ATTENTION_AGENT_CONFIG_CHANGED", params: {} }, ["acceptAgentConfig"]],
      [
        { code: "ATTENTION_INTEGRITY_CHANGED", params: { items: JSON.stringify([{ code: "INTEGRITY_HOOKS_CHANGED", detail: "" }]) } },
        ["acceptIntegrity"],
      ],
      [
        { code: "ATTENTION_INTEGRITY_CHANGED", params: { items: JSON.stringify([{ code: "INTEGRITY_HEAD_MOVED", detail: "" }]) } },
        [],
      ],
    ] as [AttentionReason, string[]][])("shows the checkboxes for %j", async (reason, expected) => {
      await openRetry(reason);
      expect(checkboxes()).toEqual(expected);
      for (const name of expected) {
        const help = container.querySelector(`[data-help="${name}"]`);
        expect(help?.textContent).toBe(i18n.t(`workflow:retry.${name}Help`));
      }
    });

    it("passes the checked flags to the retry command", async () => {
      await openRetry({ code: "ATTENTION_SCREENING_FLAGGED", params: {} });
      await click(container.querySelector<HTMLInputElement>('input[name="acceptScreening"]')!);
      await click(confirmButton());
      expect(api.retryTask).toHaveBeenCalledWith(ROOT, "t1", {
        acceptScreening: true,
        acceptAgentConfig: false,
        acceptIntegrity: false,
      });
      expect(container.querySelector(".workflow-retry")).toBeNull();
    });

    it("re-opens with the integrity checkbox when the backend requires the acknowledgement", async () => {
      api.retryTask.mockRejectedValueOnce({ code: "WORKFLOW_INTEGRITY_ACK_REQUIRED", message: "" });
      await openRetry({ code: "ATTENTION_TIMEOUT", params: {} });
      await click(confirmButton());
      expect(showMessage).not.toHaveBeenCalled();
      expect(checkboxes()).toEqual(["acceptIntegrity"]);
      expect(container.querySelector(".workflow-retry")!.textContent).toContain(
        i18n.t("workflow:codes.WORKFLOW_INTEGRITY_ACK_REQUIRED"),
      );
      await click(container.querySelector<HTMLInputElement>('input[name="acceptIntegrity"]')!);
      await click(confirmButton());
      expect(api.retryTask).toHaveBeenLastCalledWith(ROOT, "t1", {
        acceptScreening: false,
        acceptAgentConfig: false,
        acceptIntegrity: true,
      });
    });

    it("cancels without retrying", async () => {
      await openRetry({ code: "ATTENTION_TIMEOUT", params: {} });
      await click(container.querySelector<HTMLButtonElement>(".workflow-retry__cancel")!);
      expect(container.querySelector(".workflow-retry")).toBeNull();
      expect(api.retryTask).not.toHaveBeenCalled();
    });
  });
});
