// @vitest-environment happy-dom
import { act } from "react";
import { createRoot } from "react-dom/client";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import type { Stage, Task, TaskDetail, TaskMeta, WorkflowRun } from "@/shared/types/workflow";

vi.mock("../../lib/workflow-api", () => ({
  workflowApi: {
    taskDetail: vi.fn(),
    listWorkflows: vi.fn(),
    listTasks: vi.fn(),
    listRuns: vi.fn(),
  },
  subscribeWorkflowEvents: vi.fn(),
}));
vi.mock("@/stores/dialog-store", () => ({ showMessage: vi.fn(), showConfirm: vi.fn(), showPrompt: vi.fn() }));

import i18n from "@/shared/i18n";
import { formatAttention } from "../../lib/format";
import { workflowApi } from "../../lib/workflow-api";
import { type ProjectState, useWorkflowStore } from "../../workflow-store";
import { TaskDetailModal } from "../TaskDetailModal";

(globalThis as typeof globalThis & { IS_REACT_ACT_ENVIRONMENT?: boolean }).IS_REACT_ACT_ENVIRONMENT = true;

const ROOT = "C:\\work\\app";
const api = vi.mocked(workflowApi);

function stage(id: string, role: Stage["role"], name: string): Stage {
  return {
    id,
    role,
    name,
    prompt: "",
    completionCriteria: "",
    provider: "claude",
    model: null,
    requiresApproval: false,
    timeoutMinutes: 60,
  };
}

function task(id: string, patch: Partial<TaskMeta> = {}, body = "Body"): Task {
  return {
    meta: {
      schemaVersion: 1,
      id,
      title: `Task ${id}`,
      status: "inbox",
      rootId: "t1",
      parentId: null,
      workflowId: "wf1",
      stageId: "s-design",
      role: "design",
      autoGenerated: false,
      archived: false,
      createdAt: "2026-09-01T00:00:00Z",
      updatedAt: "2026-09-01T00:00:00Z",
      attention: null,
      history: [],
      awaiting: null,
      planApproved: false,
      userInput: null,
      screeningAck: null,
      ...patch,
    },
    body,
  };
}

function runOf(patch: Partial<WorkflowRun> = {}): WorkflowRun {
  return {
    schemaVersion: 1,
    rootTaskId: "t1",
    workflow: {
      id: "wf1",
      name: "Standard",
      enabled: true,
      archived: false,
      stages: [stage("s-design", "design", "Design stage"), stage("s-impl", "implement", "Build stage"), stage("s-review", "review", "Check stage")],
      reviewReturnTo: "design",
      maxReentryCount: 5,
      maxConcurrentRuns: 1,
      designDocPath: null,
      issueTracking: "off",
    },
    status: "active",
    currentTaskId: "t2",
    reentryCount: 1,
    worktree: { path: "C:\\wt", branch: "workflow/t1", baseBranch: "main", baseCommit: "abc" },
    attempts: [
      {
        attemptId: "a1",
        taskId: "t2",
        stageId: "s-impl",
        sessionId: "x",
        runnerPid: null,
        startedAt: "2026-09-02T00:00:00Z",
        finishedAt: "2026-09-02T01:00:00Z",
        outcome: "awaiting_user",
        mode: "plan",
        userInput: null,
      },
      {
        attemptId: "a2",
        taskId: "t2",
        stageId: "s-impl",
        sessionId: "y",
        runnerPid: null,
        startedAt: "2026-09-03T00:00:00Z",
        finishedAt: "2026-09-03T01:00:00Z",
        outcome: "attention",
        mode: "execute",
        userInput: null,
      },
      {
        attemptId: "other",
        taskId: "t1",
        stageId: "s-design",
        sessionId: "z",
        runnerPid: null,
        startedAt: "2026-09-01T00:00:00Z",
        finishedAt: "2026-09-01T01:00:00Z",
        outcome: "completed",
        mode: "single",
        userInput: null,
      },
    ],
    pendingTransition: null,
    integrityBaseline: null,
    createdAt: "2026-09-01T00:00:00Z",
    updatedAt: "2026-09-03T01:00:00Z",
    acknowledgedAgentConfig: [],
    ...patch,
  };
}

const attention = { code: "ATTENTION_STAGE_REPORTED", params: { reason: "Tests fail", items: '["a.ts","b.ts"]' } };

const rootTask = task("t1", { status: "completed" });
const current = task(
  "t2",
  {
    status: "attention",
    parentId: "t1",
    stageId: "s-impl",
    role: "implement",
    createdAt: "2026-09-02T00:00:00Z",
    updatedAt: "2026-09-03T01:00:00Z",
    attention,
    history: [
      { at: "2026-09-02T00:00:00Z", from: null, to: "inbox", reason: null },
      { at: "2026-09-03T01:00:00Z", from: "running", to: "attention", reason: attention },
    ],
  },
  "# Goal\n\n**Ship** it",
);

function detail(patch: Partial<TaskDetail> = {}): TaskDetail {
  return {
    task: current,
    run: runOf(),
    latestOutput: "## Result\n\nAll *done*",
    logTail: ["line one", "line two"],
    ...patch,
  };
}

function project(tasks: Task[], runs: WorkflowRun[]): ProjectState {
  return {
    root: ROOT,
    workflows: [],
    workflowWarnings: [],
    tasks,
    taskWarnings: [],
    runs,
    progress: {},
    loading: false,
    refreshing: false,
    loaded: true,
    error: null,
  };
}

const initialStore = useWorkflowStore.getState();

describe("TaskDetailModal", () => {
  let root: ReturnType<typeof createRoot>;
  let container: HTMLDivElement;

  beforeEach(async () => {
    await i18n.changeLanguage("en");
    vi.clearAllMocks();
    useWorkflowStore.setState(initialStore, true);
    useWorkflowStore.setState({
      activeRoot: ROOT,
      projects: { [ROOT]: project([rootTask, current], [runOf()]) },
      selectedTaskId: "t2",
    });
    api.taskDetail.mockResolvedValue(detail());
    container = document.createElement("div");
    document.body.appendChild(container);
    root = createRoot(container);
  });

  afterEach(async () => {
    await act(async () => root.unmount());
    container.remove();
  });

  async function render() {
    await act(async () => root.render(<TaskDetailModal />));
  }

  function section(name: string) {
    return container.querySelector<HTMLElement>(`[data-section="${name}"]`);
  }

  it("renders nothing without a selected task", async () => {
    useWorkflowStore.setState({ selectedTaskId: null });
    await render();
    expect(container.innerHTML).toBe("");
    expect(api.taskDetail).not.toHaveBeenCalled();
  });

  it("renders every section from the task detail", async () => {
    await render();
    expect(api.taskDetail).toHaveBeenCalledWith(ROOT, "t2");
    const dialog = container.querySelector<HTMLElement>('[role="dialog"]')!;
    expect(dialog.getAttribute("aria-modal")).toBe("true");
    expect(dialog.querySelector(".workflow-detail__title")?.textContent).toBe("Task t2");
    expect(dialog.querySelector(".workflow-detail__status")?.textContent).toBe(i18n.t("workflow:status.attention"));

    // Markdown body and latest output.
    expect(section("body")!.querySelector("h1")?.textContent).toBe("Goal");
    expect(section("body")!.querySelector("strong")?.textContent).toBe("Ship");
    expect(section("output")!.querySelector("h2")?.textContent).toBe("Result");
    // The latest finished attempt's labels.
    expect(section("output")!.textContent).toContain(i18n.t("workflow:mode.execute"));
    expect(section("output")!.textContent).toContain(i18n.t("workflow:outcome.attention"));

    // Attention reason with its items.
    expect(section("attention")!.textContent).toContain(formatAttention(attention).text);
    expect([...section("attention")!.querySelectorAll("li")].map((li) => li.textContent)).toEqual(["a.ts", "b.ts"]);

    // Attempts of this task only, newest first, with stage names from the run snapshot.
    const rows = [...section("attempts")!.querySelectorAll("tbody tr")];
    expect(rows).toHaveLength(2);
    expect(rows[0].textContent).toContain(i18n.t("workflow:mode.execute"));
    expect(rows[0].textContent).toContain("Build stage");
    expect(rows[1].textContent).toContain(i18n.t("workflow:mode.plan"));

    // History with formatted reasons.
    const history = section("history")!;
    expect(history.querySelectorAll("li")).toHaveLength(2);
    expect(history.textContent).toContain(i18n.t("workflow:status.running"));
    expect(history.textContent).toContain(formatAttention(attention).text);

    // Run info.
    const run = section("run")!;
    expect(run.textContent).toContain(i18n.t("workflow:runStatus.active"));
    expect(run.textContent).toContain(i18n.t("workflow:detail.reentryValue", { count: 1, max: 5 }));
    expect(run.textContent).toContain("workflow/t1");
    expect(run.textContent).toContain("main");
    expect(run.textContent).toContain(i18n.t("workflow:detail.transitionValue", { from: "Design stage", to: "Build stage" }));

    // Log tail as text.
    expect(section("log")!.querySelector("pre")?.textContent).toBe("line one\nline two");
  });

  it("shows the plan approval and the question as plain text", async () => {
    const waiting = task("t2", { status: "awaiting_user", awaiting: { kind: "question", question: "<b>Which DB?</b>" } });
    api.taskDetail.mockResolvedValue(detail({ task: waiting }));
    await render();
    const awaiting = section("awaiting")!;
    expect(awaiting.textContent).toContain("<b>Which DB?</b>");
    expect(awaiting.querySelector("b")).toBeNull();

    api.taskDetail.mockResolvedValue(
      detail({ task: task("t2", { status: "awaiting_user", awaiting: { kind: "plan_approval", question: null } }) }),
    );
    await act(async () => root.unmount());
    root = createRoot(container);
    await render();
    expect(section("awaiting")!.textContent).toContain(i18n.t("workflow:detail.planApproval"));
  });

  it("renders a hostile body and output inert", async () => {
    const hostile =
      '<img src=x onerror="alert(1)"><script>window.__pwned = 1</script>[link](javascript:alert(1)) <div onclick="x()">raw</div> **still bold**';
    api.taskDetail.mockResolvedValue(detail({ task: { ...current, body: hostile }, latestOutput: hostile }));
    await render();
    for (const name of ["body", "output"]) {
      const el = section(name)!;
      expect(el.querySelector("script")).toBeNull();
      expect(el.querySelector("[onerror]")).toBeNull();
      expect(el.querySelector("[onclick]")).toBeNull();
      expect(el.querySelector('a[href^="javascript:"]')).toBeNull();
      expect(el.querySelector("strong")?.textContent).toBe("still bold");
    }
    expect((window as typeof window & { __pwned?: number }).__pwned).toBeUndefined();
  });

  it("closes on Escape, on the close button and on an overlay click", async () => {
    await render();
    const dialog = container.querySelector<HTMLElement>('[role="dialog"]')!;
    await act(async () => dialog.dispatchEvent(new KeyboardEvent("keydown", { key: "Escape", bubbles: true })));
    expect(useWorkflowStore.getState().selectedTaskId).toBeNull();

    await act(async () => useWorkflowStore.setState({ selectedTaskId: "t2" }));
    // A click inside the dialog keeps it open.
    await act(async () => dialog.ownerDocument.querySelector<HTMLElement>('[role="dialog"]')!.click());
    expect(useWorkflowStore.getState().selectedTaskId).toBe("t2");
    await act(async () => container.querySelector<HTMLElement>(".workflow-detail-overlay")!.click());
    expect(useWorkflowStore.getState().selectedTaskId).toBeNull();

    await act(async () => useWorkflowStore.setState({ selectedTaskId: "t2" }));
    await act(async () => container.querySelector<HTMLButtonElement>(".workflow-detail__close")!.click());
    expect(useWorkflowStore.getState().selectedTaskId).toBeNull();
  });

  it("reloads when the task or its run changes", async () => {
    await render();
    expect(api.taskDetail).toHaveBeenCalledTimes(1);
    const updated = task("t2", { ...current.meta, updatedAt: "2026-09-04T00:00:00Z" }, current.body);
    await act(async () => useWorkflowStore.setState({ projects: { [ROOT]: project([rootTask, updated], [runOf()]) } }));
    expect(api.taskDetail).toHaveBeenCalledTimes(2);
    await act(async () =>
      useWorkflowStore.setState({
        projects: { [ROOT]: project([rootTask, updated], [runOf({ updatedAt: "2026-09-05T00:00:00Z" })]) },
      }),
    );
    expect(api.taskDetail).toHaveBeenCalledTimes(3);
    // Unrelated changes do not reload.
    await act(async () =>
      useWorkflowStore.setState({
        projects: {
          [ROOT]: project([rootTask, updated, task("x", { rootId: "x" })], [runOf({ updatedAt: "2026-09-05T00:00:00Z" })]),
        },
      }),
    );
    expect(api.taskDetail).toHaveBeenCalledTimes(3);
  });

  it("shows a load error inside the modal", async () => {
    api.taskDetail.mockRejectedValue({ code: "TASK_NOT_FOUND", message: "gone" });
    await render();
    expect(container.querySelector('[role="alert"]')?.textContent).toContain(i18n.t("workflow:codes.TASK_NOT_FOUND"));
  });
});
