// @vitest-environment happy-dom
import { act } from "react";
import { createRoot } from "react-dom/client";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import type { Task, TaskMeta, TaskStatus, WorkflowRun } from "@/shared/types/workflow";

vi.mock("../../lib/workflow-api", () => ({ workflowApi: {}, subscribeWorkflowEvents: vi.fn() }));
vi.mock("@/stores/dialog-store", () => ({ showMessage: vi.fn(), showConfirm: vi.fn(), showPrompt: vi.fn() }));

import i18n from "@/shared/i18n";
import { formatAttention } from "../../lib/format";
import { type ProjectState, type TaskProgress, useWorkflowStore } from "../../workflow-store";
import { Workspace } from "../Workspace";

(globalThis as typeof globalThis & { IS_REACT_ACT_ENVIRONMENT?: boolean }).IS_REACT_ACT_ENVIRONMENT = true;

const ROOT = "C:\\work\\my-project";

function task(id: string, patch: Partial<TaskMeta> = {}): Task {
  return {
    meta: {
      schemaVersion: 1,
      id,
      title: `Task ${id}`,
      status: "inbox",
      rootId: id,
      parentId: null,
      workflowId: "wf1",
      stageId: null,
      role: "design",
      autoGenerated: false,
      archived: false,
      createdAt: "2026-09-01T00:00:00Z",
      updatedAt: "2026-09-01T00:00:00Z",
      attention: null,
      history: [],
      awaiting: null,
      planApproved: false,
      userInput: null,
      screeningAck: null,
      ...patch,
    },
    // A Markdown body that must never be rendered on a card.
    body: "# Heading\n\n**bold**",
  };
}

function run(rootTaskId: string, status: WorkflowRun["status"], currentTaskId = rootTaskId): WorkflowRun {
  return {
    schemaVersion: 1,
    rootTaskId,
    workflow: {} as WorkflowRun["workflow"],
    status,
    currentTaskId,
    reentryCount: 0,
    worktree: null,
    attempts: [],
    pendingTransition: null,
    integrityBaseline: null,
    createdAt: "2026-09-01T00:00:00Z",
    updatedAt: "2026-09-01T00:00:00Z",
    acknowledgedAgentConfig: [],
  };
}

function project(tasks: Task[], extra: Partial<ProjectState> = {}): ProjectState {
  return {
    root: ROOT,
    workflows: [],
    workflowWarnings: [],
    tasks,
    taskWarnings: [],
    runs: [],
    progress: {},
    loading: false,
    refreshing: false,
    loaded: true,
    error: null,
    ...extra,
  };
}

const initialStore = useWorkflowStore.getState();

describe("Workspace", () => {
  let root: ReturnType<typeof createRoot>;
  let container: HTMLDivElement;

  beforeEach(async () => {
    await i18n.changeLanguage("en");
    useWorkflowStore.setState(initialStore, true);
    container = document.createElement("div");
    document.body.appendChild(container);
    root = createRoot(container);
  });

  afterEach(async () => {
    await act(async () => root.unmount());
    container.remove();
  });

  function setProject(p: ProjectState) {
    useWorkflowStore.setState({ activeRoot: ROOT, projects: { [ROOT]: p } });
  }

  async function render() {
    await act(async () => root.render(<Workspace />));
  }

  function column(status: TaskStatus) {
    return container.querySelector<HTMLElement>(`.workflow-kanban__column[data-status="${status}"]`);
  }

  function card(id: string) {
    return container.querySelector<HTMLButtonElement>(`[data-task-id="${id}"]`);
  }

  it("shows the project name and the empty state", async () => {
    setProject(project([]));
    await render();
    expect(container.querySelector(".workflow-workspace__title")?.textContent).toBe("my-project");
    expect(container.textContent).toContain(i18n.t("workflow:emptyBoard"));
  });

  it("renders kanban columns in status order with counts, newest first", async () => {
    setProject(
      project([
        task("a", { status: "running", updatedAt: "2026-09-01T00:00:00Z" }),
        task("b", { status: "running", updatedAt: "2026-09-03T00:00:00Z" }),
        task("c", { status: "completed" }),
        task("d", { status: "cancelled" }),
      ]),
    );
    await render();
    const statuses = [...container.querySelectorAll<HTMLElement>(".workflow-kanban__column")].map((c) => c.dataset.status);
    expect(statuses).toEqual(["inbox", "running", "awaiting_user", "attention", "on_hold", "completed"]);
    const running = column("running")!;
    expect(running.querySelector(".workflow-kanban__title")?.textContent).toBe(i18n.t("workflow:status.running"));
    expect(running.querySelector(".workflow-kanban__count")?.textContent).toBe("2");
    expect(column("inbox")!.querySelector(".workflow-kanban__count")?.textContent).toBe("0");
    expect([...running.querySelectorAll<HTMLElement>("[data-task-id]")].map((c) => c.dataset.taskId)).toEqual(["b", "a"]);
  });

  it("applies the archived, cancelled and workflow filters", async () => {
    setProject(
      project([
        task("a"),
        task("archived", { archived: true }),
        task("cancelled", { status: "cancelled" }),
        task("other", { workflowId: "wf2" }),
      ]),
    );
    await render();
    expect(card("a")).not.toBeNull();
    expect(card("archived")).toBeNull();
    expect(card("cancelled")).toBeNull();
    expect(card("other")).not.toBeNull();

    await act(async () => useWorkflowStore.getState().setFilters({ showArchived: true, showCancelled: true, workflowId: "wf1" }));
    expect(card("archived")).not.toBeNull();
    expect(card("cancelled")).not.toBeNull();
    expect(column("cancelled")).not.toBeNull();
    expect(card("other")).toBeNull();
  });

  it("shows the attention text, the awaiting kind and the progress line", async () => {
    const attention = { code: "ATTENTION_INTERRUPTED", params: {} };
    const progress: Record<string, TaskProgress> = { run1: { text: "Editing src/main.ts", kind: "tool", at: 1 } };
    setProject(
      project(
        [
          task("att", { status: "attention", attention }),
          task("wait", { status: "awaiting_user", awaiting: { kind: "plan_approval", question: null } }),
          task("run1", { status: "running" }),
        ],
        { progress },
      ),
    );
    await render();
    expect(card("att")!.textContent).toContain(formatAttention(attention).text);
    expect(card("wait")!.textContent).toContain(i18n.t("workflow:awaiting.plan_approval"));
    expect(card("run1")!.querySelector(".workflow-card__progress")?.textContent).toBe("Editing src/main.ts");
    expect(card("run1")!.textContent).toContain(i18n.t("workflow:role.design"));
    // Markdown bodies are never rendered on cards.
    expect(container.querySelector("h1, strong")).toBeNull();
  });

  it("marks the waiting current task of an active run as holding a slot", async () => {
    const attention = { code: "X", params: {} };
    setProject(
      project(
        [
          task("held", { status: "attention", rootId: "r1", attention }),
          // Same run, but not its current task: the run's one slot is shown once.
          task("old", { status: "attention", rootId: "r1", attention }),
          task("free", { status: "attention", rootId: "r2", attention }),
          task("wait", { status: "awaiting_user", rootId: "r3", awaiting: { kind: "question", question: "?" } }),
          task("busy", { status: "running", rootId: "r4" }),
        ],
        {
          runs: [
            run("r1", "active", "held"),
            run("r2", "awaiting_merge", "free"),
            run("r3", "active", "wait"),
            run("r4", "active", "busy"),
          ],
        },
      ),
    );
    await render();
    const badge = card("held")!.querySelector<HTMLElement>(".workflow-card__slot");
    expect(badge?.title).toBe(i18n.t("workflow:workspace.holdsSlot"));
    expect(card("wait")!.querySelector(".workflow-card__slot")).not.toBeNull();
    expect(card("old")!.querySelector(".workflow-card__slot")).toBeNull();
    expect(card("free")!.querySelector(".workflow-card__slot")).toBeNull();
    expect(card("busy")!.querySelector(".workflow-card__slot")).toBeNull();
  });

  it("shows the attach error instead of loading", async () => {
    useWorkflowStore.setState({ activeRoot: null, attachError: "Attach failed: detail" });
    await render();
    expect(container.querySelector('[role="alert"]')?.textContent).toBe("Attach failed: detail");
    expect(container.textContent).not.toContain(i18n.t("workflow:loading"));
  });

  it("shows loading until the first load completes", async () => {
    setProject(project([], { loaded: false, loading: true }));
    await render();
    expect(container.textContent).toContain(i18n.t("workflow:loading"));
    expect(container.textContent).not.toContain(i18n.t("workflow:emptyBoard"));
  });

  it("shows the load error before the first load completes", async () => {
    setProject(project([], { loaded: false, error: "Load failed" }));
    await render();
    expect(container.querySelector('[role="alert"]')?.textContent).toBe("Load failed");
    expect(container.textContent).not.toContain(i18n.t("workflow:loading"));
  });

  it("labels columns and pluralizes the count tooltip", async () => {
    setProject(project([task("a")]));
    await render();
    const inbox = column("inbox")!;
    const label = document.getElementById(inbox.getAttribute("aria-labelledby")!);
    expect(label?.textContent).toBe(i18n.t("workflow:status.inbox"));
    expect(inbox.querySelector<HTMLElement>(".workflow-kanban__count")!.title).toBe("1 task");
    expect(column("running")!.querySelector<HTMLElement>(".workflow-kanban__count")!.title).toBe("0 tasks");
  });

  it("falls back to the raw awaiting kind when it has no translation", async () => {
    setProject(
      project([task("w", { status: "awaiting_user", awaiting: { kind: "future_kind" as never, question: null } })]),
    );
    await render();
    expect(card("w")!.querySelector(".workflow-card__awaiting")?.textContent).toBe("future_kind");
  });

  it("uses the status CSS variable as the card background", async () => {
    setProject(project([task("a", { status: "awaiting_user" }), task("b", { status: "on_hold" })]));
    await render();
    expect(card("a")!.style.background).toBe("var(--task-status-awaiting-user-background)");
    expect(card("b")!.style.background).toBe("var(--task-status-on-hold-background)");
  });

  it("opens the task on click; cards are buttons", async () => {
    setProject(project([task("a")]));
    await render();
    expect(card("a")!.tagName).toBe("BUTTON");
    await act(async () => card("a")!.click());
    expect(useWorkflowStore.getState().selectedTaskId).toBe("a");
  });

  it("places tasks by role and status in the matrix", async () => {
    setProject(
      project([
        task("d1", { role: "design", status: "inbox" }),
        task("i1", { role: "implement", status: "running" }),
        task("i2", { role: "implement", status: "running", updatedAt: "2026-09-02T00:00:00Z" }),
        task("r1", { role: "review", status: "completed" }),
      ]),
    );
    await act(async () => useWorkflowStore.getState().setFilters({ view: "matrix" }));
    await render();
    const cell = (role: string, status: TaskStatus) =>
      container.querySelector<HTMLElement>(`.workflow-matrix__cell[data-role="${role}"][data-status="${status}"]`)!;
    expect(container.querySelector(".workflow-kanban")).toBeNull();
    expect(cell("design", "inbox").querySelector("[data-task-id]")?.getAttribute("data-task-id")).toBe("d1");
    expect(cell("implement", "running").querySelector(".workflow-matrix__count")?.textContent).toBe("2");
    expect(cell("review", "completed").textContent).toContain("Task r1");
    expect(cell("design", "running").querySelector("[data-task-id]")).toBeNull();
    await act(async () => cell("implement", "running").querySelector<HTMLButtonElement>("[data-task-id]")!.click());
    expect(useWorkflowStore.getState().selectedTaskId).toBe("i2");
  });

  it("switches the view from the header toggle", async () => {
    setProject(project([task("a")]));
    await render();
    const matrixBtn = [...container.querySelectorAll<HTMLButtonElement>(".workflow-workspace__view-btn")].find(
      (b) => b.textContent === i18n.t("workflow:panel.viewMatrix"),
    )!;
    await act(async () => matrixBtn.click());
    expect(useWorkflowStore.getState().filters.view).toBe("matrix");
    expect(container.querySelector(".workflow-matrix")).not.toBeNull();
  });

  it("renders 300 tasks within the time bound", async () => {
    const statuses: TaskStatus[] = ["inbox", "running", "awaiting_user", "attention", "on_hold", "completed"];
    const tasks = Array.from({ length: 300 }, (_, i) =>
      task(`t${i}`, {
        status: statuses[i % statuses.length],
        updatedAt: new Date(Date.UTC(2026, 8, 1, 0, i)).toISOString(),
        attention: { code: "ATTENTION_INTERRUPTED", params: {} },
        awaiting: { kind: "question", question: "?" },
      }),
    );
    setProject(project(tasks));
    const started = performance.now();
    await render();
    expect(performance.now() - started).toBeLessThan(1000);
    expect(container.querySelectorAll("[data-task-id]").length).toBe(300);
  });
});
