import type { ThemePreset } from "./types";
import {
  mdiumLight,
  mdiumDark,
  ocOpencodeDark,
  ocOpencodeLight,
  ocCatppuccinDark,
  ocCatppuccinLight,
  ocCatppuccinFrappe,
  ocCatppuccinMacchiato,
  ocDraculaDark,
  ocDraculaLight,
  ocGithubDark,
  ocGithubLight,
  ocNordDark,
  ocNordLight,
  ocOneDarkDark,
  ocOneDarkLight,
  ocTokyonightDark,
  ocTokyonightLight,
  ocSolarizedDark,
  ocSolarizedLight,
  ocGruvboxDark,
  ocGruvboxLight,
  ocRosepineDark,
  ocRosepineLight,
  ocMonokaiDark,
  ocMonokaiLight,
  ocAura,
  ocAyu,
  ocCarbonfoxDark,
  ocCarbonfoxLight,
  ocCobalt2Dark,
  ocCobalt2Light,
  ocCursorDark,
  ocCursorLight,
  ocEverforestDark,
  ocEverforestLight,
  ocFlexokiDark,
  ocFlexokiLight,
  ocKanagawaDark,
  ocKanagawaLight,
  ocLucentOrngDark,
  ocLucentOrngLight,
  ocMaterialDark,
  ocMaterialLight,
  ocMatrixDark,
  ocMatrixLight,
  ocMercuryDark,
  ocMercuryLight,
  ocNightowl,
  ocOrngDark,
  ocOrngLight,
  ocOsakaJadeDark,
  ocOsakaJadeLight,
  ocPalenightDark,
  ocPalenightLight,
  ocSynthwave84Dark,
  ocSynthwave84Light,
  ocVercelDark,
  ocVercelLight,
  ocVesperDark,
  ocVesperLight,
  ocZenburnDark,
  ocZenburnLight,
} from "./presets";

export type { ThemePreset, ThemeColors, ThemeType } from "./types";

export const themePresets: ThemePreset[] = [
  mdiumLight,
  mdiumDark,
  ocOpencodeDark,
  ocOpencodeLight,
  ocCatppuccinDark,
  ocCatppuccinLight,
  ocCatppuccinFrappe,
  ocCatppuccinMacchiato,
  ocDraculaDark,
  ocDraculaLight,
  ocGithubDark,
  ocGithubLight,
  ocNordDark,
  ocNordLight,
  ocOneDarkDark,
  ocOneDarkLight,
  ocTokyonightDark,
  ocTokyonightLight,
  ocSolarizedDark,
  ocSolarizedLight,
  ocGruvboxDark,
  ocGruvboxLight,
  ocRosepineDark,
  ocRosepineLight,
  ocMonokaiDark,
  ocMonokaiLight,
  ocAura,
  ocAyu,
  ocCarbonfoxDark,
  ocCarbonfoxLight,
  ocCobalt2Dark,
  ocCobalt2Light,
  ocCursorDark,
  ocCursorLight,
  ocEverforestDark,
  ocEverforestLight,
  ocFlexokiDark,
  ocFlexokiLight,
  ocKanagawaDark,
  ocKanagawaLight,
  ocLucentOrngDark,
  ocLucentOrngLight,
  ocMaterialDark,
  ocMaterialLight,
  ocMatrixDark,
  ocMatrixLight,
  ocMercuryDark,
  ocMercuryLight,
  ocNightowl,
  ocOrngDark,
  ocOrngLight,
  ocOsakaJadeDark,
  ocOsakaJadeLight,
  ocPalenightDark,
  ocPalenightLight,
  ocSynthwave84Dark,
  ocSynthwave84Light,
  ocVercelDark,
  ocVercelLight,
  ocVesperDark,
  ocVesperLight,
  ocZenburnDark,
  ocZenburnLight,
];

export const DEFAULT_THEME_ID = "oc-opencode-dark";

/** Migration map from old theme IDs to new opencode-synced IDs */
const LEGACY_THEME_MAP: Record<string, string> = {
  "mdium-light": "mdium-light",
  "mdium-dark": "mdium-dark",
  "github-light": "oc-github-light",
  "github-dark": "oc-github-dark",
  "solarized-light": "oc-solarized-light",
  "solarized-dark": "oc-solarized-dark",
  nord: "oc-nord-dark",
  dracula: "oc-dracula-dark",
  "one-dark": "oc-one-dark-dark",
  "tokyo-night": "oc-tokyonight-dark",
};

export function getThemeById(id: string): ThemePreset {
  const resolved = LEGACY_THEME_MAP[id] ?? id;
  return themePresets.find((t) => t.id === resolved) ?? ocOpencodeDark;
}
