// @vitest-environment happy-dom
import { afterEach, beforeAll, beforeEach, describe, expect, it, vi } from "vitest";
import type {
  IntakeChangedEvent,
  IntakeSessionView,
  ProgressEvent,
  RunChangedEvent,
  Task,
  TaskChangedEvent,
  Workflow,
  WorkflowsChangedEvent,
} from "@/shared/types/workflow";
import type { WorkflowEventHandlers } from "../lib/workflow-api";

const api = vi.hoisted(() => ({
  attach: vi.fn(),
  listWorkflows: vi.fn(),
  listTasks: vi.fn(),
  listRuns: vi.fn(),
  intakeList: vi.fn(),
}));
const subscribe = vi.hoisted(() => vi.fn());
const subscribeIntake = vi.hoisted(() => vi.fn());
const subscribeWorkflowsChanged = vi.hoisted(() => vi.fn());
const showMessage = vi.hoisted(() => vi.fn());
vi.mock("../lib/workflow-api", () => ({
  workflowApi: api,
  subscribeWorkflowEvents: subscribe,
  subscribeIntakeChanged: subscribeIntake,
  subscribeWorkflowsChanged,
}));
vi.mock("@/stores/dialog-store", () => ({ showMessage }));

import i18n from "@/shared/i18n";
import { startWorkflowEventBridge, useWorkflowStore } from "../workflow-store";

const ROOT_A = "C:\\projA";
const ROOT_B = "C:\\projB";

function task(id: string, status: Task["meta"]["status"] = "inbox"): Task {
  return {
    meta: {
      schemaVersion: 1,
      id,
      title: id,
      status,
      rootId: id,
      parentId: null,
      workflowId: "wf1",
      stageId: null,
      role: null,
      autoGenerated: false,
      archived: false,
      createdAt: "",
      updatedAt: "",
      attention: null,
      history: [],
      awaiting: null,
      planApproved: false,
      userInput: null,
      screeningAck: null,
      issue: null,
      pendingIssueEntry: null,
    },
    body: "",
  };
}

const WORKFLOW = { id: "wf1", name: "WF" } as Workflow;

function intake(id: string): IntakeSessionView {
  return { id, status: "active", busy: false } as IntakeSessionView;
}

/** Per-root intake sessions returned by the mocked `intakeList`. */
let intakesByRoot: Record<string, IntakeSessionView[]>;

/** Per-root task lists returned by the mocked `listTasks`. */
let tasksByRoot: Record<string, Task[]>;

function deferred<T>() {
  let resolve!: (v: T) => void;
  const promise = new Promise<T>((r) => {
    resolve = r;
  });
  return { promise, resolve };
}

const initialState = useWorkflowStore.getState();
let releases: (() => void)[] = [];
let handlers: WorkflowEventHandlers;
let onIntakeChanged: (e: IntakeChangedEvent) => void;
let onWorkflowsChanged: (e: WorkflowsChangedEvent) => void;
const unsubscribe = vi.hoisted(() => vi.fn());
const unsubscribeIntake = vi.hoisted(() => vi.fn());
const unsubscribeWorkflows = vi.hoisted(() => vi.fn());

async function startBridge() {
  const release = await startWorkflowEventBridge();
  releases.push(release);
  return release;
}

describe("workflow store", () => {
  beforeAll(async () => {
    await i18n.changeLanguage("en");
  });

  beforeEach(() => {
    vi.clearAllMocks();
    useWorkflowStore.setState(initialState, true);
    tasksByRoot = { [ROOT_A]: [task("a1")], [ROOT_B]: [task("b1")] };
    api.attach.mockImplementation(async (folder: string) => folder);
    api.listWorkflows.mockResolvedValue({ workflows: [WORKFLOW], warnings: [] });
    api.listTasks.mockImplementation(async (root: string) => ({ tasks: tasksByRoot[root] ?? [], warnings: [] }));
    api.listRuns.mockResolvedValue({ runs: [], warnings: [] });
    intakesByRoot = { [ROOT_A]: [intake("i1")], [ROOT_B]: [intake("i2")] };
    api.intakeList.mockImplementation(async (root: string) => ({ sessions: intakesByRoot[root] ?? [], warnings: [] }));
    subscribe.mockImplementation(async (h: WorkflowEventHandlers) => {
      handlers = h;
      return unsubscribe;
    });
    subscribeIntake.mockImplementation(async (h: (e: IntakeChangedEvent) => void) => {
      onIntakeChanged = h;
      return unsubscribeIntake;
    });
    subscribeWorkflowsChanged.mockImplementation(async (h: (e: WorkflowsChangedEvent) => void) => {
      onWorkflowsChanged = h;
      return unsubscribeWorkflows;
    });
  });

  afterEach(() => {
    for (const release of releases) release();
    releases = [];
    vi.useRealTimers();
  });

  it("activate attaches and loads the lists", async () => {
    await useWorkflowStore.getState().activate(ROOT_A);
    const s = useWorkflowStore.getState();
    expect(api.attach).toHaveBeenCalledWith(ROOT_A);
    expect(s.activeRoot).toBe(ROOT_A);
    const p = s.projects[ROOT_A];
    expect(p.workflows).toEqual([WORKFLOW]);
    expect(p.tasks.map((t) => t.meta.id)).toEqual(["a1"]);
    expect(p.runs).toEqual([]);
    expect(p.intakes.map((i) => i.id)).toEqual(["i1"]);
    expect(p.intakesLoaded).toBe(true);
    expect(api.intakeList).toHaveBeenCalledWith(ROOT_A);
    expect(p.loading).toBe(false);
    expect(p.error).toBeNull();
  });

  it("keeps the lists and stores the intake error when the intake list fails", async () => {
    api.intakeList.mockRejectedValue({ code: "WORKFLOW_PROJECT_INVALID", message: "no intakes" });
    await useWorkflowStore.getState().activate(ROOT_A);
    const p = useWorkflowStore.getState().projects[ROOT_A];
    expect(p.tasks.map((t) => t.meta.id)).toEqual(["a1"]);
    expect(p.error).toBeNull();
    expect(p.intakeError).toContain("no intakes");
    expect(p.intakesLoaded).toBe(false);
    api.intakeList.mockResolvedValue({ sessions: [intake("i3")], warnings: [] });
    await useWorkflowStore.getState().refreshIntakes(ROOT_A);
    const next = useWorkflowStore.getState().projects[ROOT_A];
    expect(next.intakeError).toBeNull();
    expect(next.intakesLoaded).toBe(true);
    expect(next.intakes.map((i) => i.id)).toEqual(["i3"]);
  });

  it("refreshes only the intakes of the event's project on intake-changed, debounced", async () => {
    vi.useFakeTimers();
    await useWorkflowStore.getState().activate(ROOT_A);
    await startBridge();
    api.intakeList.mockClear();
    api.listTasks.mockClear();
    intakesByRoot[ROOT_A] = [intake("i1"), intake("i4")];
    onIntakeChanged({ projectRoot: ROOT_A, intakeId: "i4", status: "active", busy: true });
    onIntakeChanged({ projectRoot: ROOT_A, intakeId: "i4", status: "active", busy: false });
    onIntakeChanged({ projectRoot: ROOT_B, intakeId: "i2", status: "active", busy: false });
    await vi.advanceTimersByTimeAsync(149);
    expect(api.intakeList).not.toHaveBeenCalled();
    await vi.advanceTimersByTimeAsync(1);
    expect(api.intakeList).toHaveBeenCalledTimes(1);
    expect(api.intakeList).toHaveBeenCalledWith(ROOT_A);
    expect(api.listTasks).not.toHaveBeenCalled();
    expect(useWorkflowStore.getState().projects[ROOT_A].intakes.map((i) => i.id)).toEqual(["i1", "i4"]);
  });

  it("refreshes the workflows of the event's project on workflows-changed", async () => {
    vi.useFakeTimers();
    await useWorkflowStore.getState().activate(ROOT_A);
    await startBridge();
    api.listWorkflows.mockClear();
    const renamed = { id: "wf1", name: "Renamed" } as Workflow;
    api.listWorkflows.mockResolvedValue({ workflows: [renamed], warnings: [] });
    onWorkflowsChanged({ projectRoot: ROOT_B });
    onWorkflowsChanged({ projectRoot: ROOT_A });
    await vi.advanceTimersByTimeAsync(150);
    expect(api.listWorkflows).toHaveBeenCalledTimes(1);
    expect(api.listWorkflows).toHaveBeenCalledWith(ROOT_A);
    expect(useWorkflowStore.getState().projects[ROOT_A].workflows).toEqual([renamed]);
  });

  it("removes every listener when the bridge is released and fails as a whole", async () => {
    const release = await startWorkflowEventBridge();
    release();
    await Promise.resolve();
    expect(unsubscribe).toHaveBeenCalledTimes(1);
    expect(unsubscribeIntake).toHaveBeenCalledTimes(1);
    expect(unsubscribeWorkflows).toHaveBeenCalledTimes(1);

    vi.clearAllMocks();
    subscribeWorkflowsChanged.mockRejectedValue(new Error("denied"));
    await expect(startWorkflowEventBridge()).rejects.toThrow("denied");
    // The listeners that did register are removed again.
    expect(unsubscribe).toHaveBeenCalledTimes(1);
    expect(unsubscribeIntake).toHaveBeenCalledTimes(1);
  });

  it("keeps activeRoot on the latest folder when switching mid-load", async () => {
    const attachA = deferred<string>();
    api.attach.mockImplementation((folder: string) =>
      folder === ROOT_A ? attachA.promise : Promise.resolve(folder),
    );
    const first = useWorkflowStore.getState().activate(ROOT_A);
    await useWorkflowStore.getState().activate(ROOT_B);
    attachA.resolve(ROOT_A);
    await first;
    const s = useWorkflowStore.getState();
    expect(s.activeRoot).toBe(ROOT_B);
    // The stale load is still stored under its own root.
    expect(s.projects[ROOT_A].tasks.map((t) => t.meta.id)).toEqual(["a1"]);
    expect(s.projects[ROOT_B].tasks.map((t) => t.meta.id)).toEqual(["b1"]);
  });

  it("does not show the previous folder's tasks while the new folder attaches", async () => {
    await useWorkflowStore.getState().activate(ROOT_A);
    const attachB = deferred<string>();
    api.attach.mockImplementation(() => attachB.promise);
    const pending = useWorkflowStore.getState().activate(ROOT_B);
    expect(useWorkflowStore.getState().activeRoot).toBeNull();
    attachB.resolve(ROOT_B);
    await pending;
    expect(useWorkflowStore.getState().activeRoot).toBe(ROOT_B);
  });

  it("reloads the lists when switching back to a known folder", async () => {
    await useWorkflowStore.getState().activate(ROOT_A);
    await useWorkflowStore.getState().activate(ROOT_B);
    tasksByRoot[ROOT_A] = [task("a1"), task("a2")];
    await useWorkflowStore.getState().activate(ROOT_A);
    const s = useWorkflowStore.getState();
    expect(s.activeRoot).toBe(ROOT_A);
    expect(s.projects[ROOT_A].tasks.map((t) => t.meta.id)).toEqual(["a1", "a2"]);
  });

  it("ensureActivated joins the activation in flight instead of attaching again", async () => {
    const attach = deferred<string>();
    api.attach.mockReturnValueOnce(attach.promise);
    const first = useWorkflowStore.getState().activate(ROOT_A);
    const joined = useWorkflowStore.getState().ensureActivated(ROOT_A);
    attach.resolve(ROOT_A);
    await Promise.all([first, joined]);
    expect(api.attach).toHaveBeenCalledTimes(1);
    expect(useWorkflowStore.getState().activeRoot).toBe(ROOT_A);
    // Already attached: nothing to do.
    await useWorkflowStore.getState().ensureActivated(ROOT_A);
    expect(api.attach).toHaveBeenCalledTimes(1);
    // Another folder is attached.
    await useWorkflowStore.getState().ensureActivated(ROOT_B);
    expect(api.attach).toHaveBeenLastCalledWith(ROOT_B);
    expect(useWorkflowStore.getState().activeRoot).toBe(ROOT_B);
  });

  it("activate(null) clears the active root", async () => {
    await useWorkflowStore.getState().activate(ROOT_A);
    await useWorkflowStore.getState().activate(null);
    expect(useWorkflowStore.getState().activeRoot).toBeNull();
  });

  it("ignores task and run events for another root", async () => {
    vi.useFakeTimers();
    await useWorkflowStore.getState().activate(ROOT_A);
    await startBridge();
    api.listTasks.mockClear();
    handlers.onTaskChanged?.({ projectRoot: ROOT_B, taskId: "b1", rootId: "b1", status: "running" } as TaskChangedEvent);
    handlers.onRunChanged?.({ projectRoot: ROOT_B, rootTaskId: "b1", status: "active" } as RunChangedEvent);
    await vi.advanceTimersByTimeAsync(500);
    expect(api.listTasks).not.toHaveBeenCalled();
    expect(useWorkflowStore.getState().projects[ROOT_B]).toBeUndefined();
  });

  it("debounces task events within 150 ms into one refresh", async () => {
    vi.useFakeTimers();
    await useWorkflowStore.getState().activate(ROOT_A);
    await startBridge();
    api.listTasks.mockClear();
    handlers.onTaskChanged?.({ projectRoot: ROOT_A, taskId: "a1", rootId: "a1", status: "running" });
    await vi.advanceTimersByTimeAsync(100);
    handlers.onTaskChanged?.({ projectRoot: ROOT_A, taskId: "a1", rootId: "a1", status: "completed" });
    await vi.advanceTimersByTimeAsync(149);
    expect(api.listTasks).not.toHaveBeenCalled();
    await vi.advanceTimersByTimeAsync(1);
    expect(api.listTasks).toHaveBeenCalledTimes(1);
    expect(api.listTasks).toHaveBeenCalledWith(ROOT_A);
  });

  it("refreshes only the lists, not the intakes, on task, run and workflows-changed events", async () => {
    vi.useFakeTimers();
    await useWorkflowStore.getState().activate(ROOT_A);
    await startBridge();
    api.intakeList.mockClear();
    api.listTasks.mockClear();
    handlers.onTaskChanged?.({ projectRoot: ROOT_A, taskId: "a1", rootId: "a1", status: "running" });
    await vi.advanceTimersByTimeAsync(150);
    handlers.onRunChanged?.({ projectRoot: ROOT_A, rootTaskId: "a1", status: "active" } as RunChangedEvent);
    await vi.advanceTimersByTimeAsync(150);
    onWorkflowsChanged({ projectRoot: ROOT_A });
    await vi.advanceTimersByTimeAsync(150);
    expect(api.listTasks).toHaveBeenCalledTimes(3);
    expect(api.intakeList).not.toHaveBeenCalled();
  });

  it("updates progress only for known projects", async () => {
    await useWorkflowStore.getState().activate(ROOT_A);
    await startBridge();
    const base = { attemptId: "at1", kind: "tool" as const };
    handlers.onProgress?.({ ...base, projectRoot: ROOT_A, taskId: "a1", text: "editing" } as ProgressEvent);
    handlers.onProgress?.({ ...base, projectRoot: ROOT_B, taskId: "b1", text: "other" } as ProgressEvent);
    const s = useWorkflowStore.getState();
    expect(s.projects[ROOT_A].progress.a1).toMatchObject({ text: "editing", kind: "tool" });
    expect(s.projects[ROOT_B]).toBeUndefined();
  });

  it("run shows an error dialog for a command error", async () => {
    await useWorkflowStore.getState().activate(ROOT_A);
    const result = await useWorkflowStore
      .getState()
      .run("Hold failed", () => Promise.reject({ code: "WORKFLOW_PROJECT_INVALID", message: "detail" }));
    expect(result).toBeUndefined();
    expect(showMessage).toHaveBeenCalledTimes(1);
    expect(showMessage.mock.calls[0][0]).toContain("detail");
    expect(showMessage.mock.calls[0][1]).toEqual({ title: "Hold failed", kind: "error" });
  });

  it("run refreshes silently on TRANSITION_CONFLICT", async () => {
    await useWorkflowStore.getState().activate(ROOT_A);
    api.listTasks.mockClear();
    const result = await useWorkflowStore
      .getState()
      .run("hold", () => Promise.reject({ code: "TRANSITION_CONFLICT", message: "raced" }));
    expect(result).toBeUndefined();
    expect(showMessage).not.toHaveBeenCalled();
    expect(api.listTasks).toHaveBeenCalledWith(ROOT_A);
  });

  it("run returns the result and refreshes after success", async () => {
    await useWorkflowStore.getState().activate(ROOT_A);
    api.listTasks.mockClear();
    const fn = vi.fn(async (root: string) => `done:${root}`);
    const result = await useWorkflowStore.getState().run("hold", fn);
    expect(result).toBe(`done:${ROOT_A}`);
    expect(fn).toHaveBeenCalledWith(ROOT_A);
    expect(api.listTasks).toHaveBeenCalledWith(ROOT_A);
  });

  it("run leaves the refresh after success to the events while the bridge is active", async () => {
    await useWorkflowStore.getState().activate(ROOT_A);
    await startBridge();
    api.listTasks.mockClear();
    expect(await useWorkflowStore.getState().run("hold", async () => "ok")).toBe("ok");
    expect(api.listTasks).not.toHaveBeenCalled();
    // Commands without change events ask for the refresh explicitly.
    await useWorkflowStore.getState().run("save", async () => "ok", { refreshNow: true });
    expect(api.listTasks).toHaveBeenCalledTimes(1);
  });

  it("run refreshes at once on TRANSITION_CONFLICT while the bridge is active", async () => {
    await useWorkflowStore.getState().activate(ROOT_A);
    await startBridge();
    api.listTasks.mockClear();
    await useWorkflowStore
      .getState()
      .run("hold", () => Promise.reject({ code: "TRANSITION_CONFLICT", message: "raced" }));
    expect(api.listTasks).toHaveBeenCalledWith(ROOT_A);
    expect(showMessage).not.toHaveBeenCalled();
  });

  it("stores a load error on the project", async () => {
    api.listTasks.mockRejectedValue({ code: "WORKFLOW_PROJECT_INVALID", message: "gone" });
    await useWorkflowStore.getState().activate(ROOT_A);
    const p = useWorkflowStore.getState().projects[ROOT_A];
    expect(p.loading).toBe(false);
    expect(p.error).toContain("gone");
  });

  it("keeps activeRoot on A for A -> B -> A when the first A attach resolves last", async () => {
    const firstA = deferred<string>();
    api.attach.mockImplementationOnce(() => firstA.promise);
    const first = useWorkflowStore.getState().activate(ROOT_A);
    await useWorkflowStore.getState().activate(ROOT_B);
    await useWorkflowStore.getState().activate(ROOT_A);
    expect(useWorkflowStore.getState().activeRoot).toBe(ROOT_A);
    firstA.resolve(ROOT_A);
    await first;
    const s = useWorkflowStore.getState();
    expect(s.activeRoot).toBe(ROOT_A);
    expect(s.projects[ROOT_A].tasks.map((t) => t.meta.id)).toEqual(["a1"]);
  });

  it("drops out-of-order refresh results", async () => {
    await useWorkflowStore.getState().activate(ROOT_A);
    const slow = deferred<{ tasks: Task[]; warnings: [] }>();
    api.listTasks.mockImplementationOnce(() => slow.promise);
    const older = useWorkflowStore.getState().refresh(ROOT_A);
    tasksByRoot[ROOT_A] = [task("new")];
    await useWorkflowStore.getState().refresh(ROOT_A);
    slow.resolve({ tasks: [task("old")], warnings: [] });
    await older;
    expect(useWorkflowStore.getState().projects[ROOT_A].tasks.map((t) => t.meta.id)).toEqual(["new"]);
  });

  it("sets loading only for the first load and refreshing for later loads", async () => {
    const slow = deferred<{ tasks: Task[]; warnings: [] }>();
    api.listTasks.mockImplementationOnce(() => slow.promise);
    const first = useWorkflowStore.getState().activate(ROOT_A);
    await vi.waitFor(() => expect(useWorkflowStore.getState().projects[ROOT_A]?.loading).toBe(true));
    slow.resolve({ tasks: [task("a1")], warnings: [] });
    await first;
    const later = deferred<{ tasks: Task[]; warnings: [] }>();
    api.listTasks.mockImplementationOnce(() => later.promise);
    const second = useWorkflowStore.getState().refresh(ROOT_A);
    let p = useWorkflowStore.getState().projects[ROOT_A];
    expect(p.loading).toBe(false);
    expect(p.refreshing).toBe(true);
    later.resolve({ tasks: [task("a1")], warnings: [] });
    await second;
    p = useWorkflowStore.getState().projects[ROOT_A];
    expect(p.loading).toBe(false);
    expect(p.refreshing).toBe(false);
  });

  it("stores an attach failure as attachError and clears it on success", async () => {
    api.attach.mockRejectedValueOnce({ code: "WORKFLOW_PROJECT_INVALID", message: "bad path" });
    await useWorkflowStore.getState().activate(ROOT_A);
    let s = useWorkflowStore.getState();
    expect(s.activeRoot).toBeNull();
    expect(s.attachError).toContain("bad path");
    expect(showMessage).not.toHaveBeenCalled();
    await useWorkflowStore.getState().activate(ROOT_B);
    s = useWorkflowStore.getState();
    expect(s.activeRoot).toBe(ROOT_B);
    expect(s.attachError).toBeNull();
  });

  it("prunes progress of tasks that are gone or no longer running on refresh", async () => {
    tasksByRoot[ROOT_A] = [task("run", "running"), task("done", "running"), task("gone", "running")];
    await useWorkflowStore.getState().activate(ROOT_A);
    await startBridge();
    for (const taskId of ["run", "done", "gone"]) {
      handlers.onProgress?.({ projectRoot: ROOT_A, taskId, attemptId: "x", kind: "message", text: taskId });
    }
    tasksByRoot[ROOT_A] = [task("run", "running"), task("done", "completed")];
    await useWorkflowStore.getState().refresh(ROOT_A);
    expect(Object.keys(useWorkflowStore.getState().projects[ROOT_A].progress)).toEqual(["run"]);
  });

  it("keeps the bridge until every caller released it", async () => {
    vi.useFakeTimers();
    await useWorkflowStore.getState().activate(ROOT_A);
    const releaseFirst = await startBridge();
    const releaseSecond = await startBridge();
    expect(subscribe).toHaveBeenCalledTimes(1);
    releaseFirst();
    releaseFirst();
    api.listTasks.mockClear();
    handlers.onTaskChanged?.({ projectRoot: ROOT_A, taskId: "a1", rootId: "a1", status: "running" });
    await vi.advanceTimersByTimeAsync(150);
    expect(api.listTasks).toHaveBeenCalledTimes(1);
    expect(unsubscribe).not.toHaveBeenCalled();
    // A refresh scheduled before the last release is cancelled.
    handlers.onTaskChanged?.({ projectRoot: ROOT_A, taskId: "a1", rootId: "a1", status: "completed" });
    releaseSecond();
    await vi.advanceTimersByTimeAsync(500);
    expect(api.listTasks).toHaveBeenCalledTimes(1);
    expect(unsubscribe).toHaveBeenCalledTimes(1);
  });

  it("shares one subscription between concurrent starts", async () => {
    const [a, b] = await Promise.all([startWorkflowEventBridge(), startWorkflowEventBridge()]);
    releases.push(a, b);
    expect(subscribe).toHaveBeenCalledTimes(1);
    a();
    expect(unsubscribe).not.toHaveBeenCalled();
    b();
    await Promise.resolve();
    expect(unsubscribe).toHaveBeenCalledTimes(1);
  });

  it("openTask and setFilters update the selection and filters", () => {
    useWorkflowStore.getState().openTask("t1");
    useWorkflowStore.getState().setFilters({ view: "matrix", showArchived: true });
    const s = useWorkflowStore.getState();
    expect(s.selectedTaskId).toBe("t1");
    expect(s.filters).toEqual({ workflowId: null, showArchived: true, showCancelled: false, view: "matrix" });
  });
});
