// @vitest-environment happy-dom
import { afterEach, beforeAll, beforeEach, describe, expect, it, vi } from "vitest";
import type {
  ProgressEvent,
  RunChangedEvent,
  Task,
  TaskChangedEvent,
  Workflow,
} from "@/shared/types/workflow";
import type { WorkflowEventHandlers } from "../lib/workflow-api";

const api = vi.hoisted(() => ({
  attach: vi.fn(),
  listWorkflows: vi.fn(),
  listTasks: vi.fn(),
  listRuns: vi.fn(),
}));
const subscribe = vi.hoisted(() => vi.fn());
const showMessage = vi.hoisted(() => vi.fn());
vi.mock("../lib/workflow-api", () => ({ workflowApi: api, subscribeWorkflowEvents: subscribe }));
vi.mock("@/stores/dialog-store", () => ({ showMessage }));

import i18n from "@/shared/i18n";
import { startWorkflowEventBridge, useWorkflowStore } from "../workflow-store";

const ROOT_A = "C:\\projA";
const ROOT_B = "C:\\projB";

function task(id: string): Task {
  return {
    meta: {
      schemaVersion: 1,
      id,
      title: id,
      status: "inbox",
      rootId: id,
      parentId: null,
      workflowId: "wf1",
      stageId: null,
      role: null,
      autoGenerated: false,
      archived: false,
      createdAt: "",
      updatedAt: "",
      attention: null,
      history: [],
      awaiting: null,
      planApproved: false,
      userInput: null,
      screeningAck: null,
    },
    body: "",
  };
}

const WORKFLOW = { id: "wf1", name: "WF" } as Workflow;

/** Per-root task lists returned by the mocked `listTasks`. */
let tasksByRoot: Record<string, Task[]>;

function deferred<T>() {
  let resolve!: (v: T) => void;
  const promise = new Promise<T>((r) => {
    resolve = r;
  });
  return { promise, resolve };
}

const initialState = useWorkflowStore.getState();
let stopBridge: (() => void) | null = null;
let handlers: WorkflowEventHandlers;

describe("workflow store", () => {
  beforeAll(async () => {
    await i18n.changeLanguage("en");
  });

  beforeEach(() => {
    vi.clearAllMocks();
    useWorkflowStore.setState(initialState, true);
    tasksByRoot = { [ROOT_A]: [task("a1")], [ROOT_B]: [task("b1")] };
    api.attach.mockImplementation(async (folder: string) => folder);
    api.listWorkflows.mockResolvedValue({ workflows: [WORKFLOW], warnings: [] });
    api.listTasks.mockImplementation(async (root: string) => ({ tasks: tasksByRoot[root] ?? [], warnings: [] }));
    api.listRuns.mockResolvedValue({ runs: [], warnings: [] });
    subscribe.mockImplementation(async (h: WorkflowEventHandlers) => {
      handlers = h;
      return () => {};
    });
  });

  afterEach(() => {
    stopBridge?.();
    stopBridge = null;
    vi.useRealTimers();
  });

  it("activate attaches and loads the lists", async () => {
    await useWorkflowStore.getState().activate(ROOT_A);
    const s = useWorkflowStore.getState();
    expect(api.attach).toHaveBeenCalledWith(ROOT_A);
    expect(s.activeRoot).toBe(ROOT_A);
    const p = s.projects[ROOT_A];
    expect(p.workflows).toEqual([WORKFLOW]);
    expect(p.tasks.map((t) => t.meta.id)).toEqual(["a1"]);
    expect(p.runs).toEqual([]);
    expect(p.loading).toBe(false);
    expect(p.error).toBeNull();
  });

  it("keeps activeRoot on the latest folder when switching mid-load", async () => {
    const attachA = deferred<string>();
    api.attach.mockImplementation((folder: string) =>
      folder === ROOT_A ? attachA.promise : Promise.resolve(folder),
    );
    const first = useWorkflowStore.getState().activate(ROOT_A);
    await useWorkflowStore.getState().activate(ROOT_B);
    attachA.resolve(ROOT_A);
    await first;
    const s = useWorkflowStore.getState();
    expect(s.activeRoot).toBe(ROOT_B);
    // The stale load is still stored under its own root.
    expect(s.projects[ROOT_A].tasks.map((t) => t.meta.id)).toEqual(["a1"]);
    expect(s.projects[ROOT_B].tasks.map((t) => t.meta.id)).toEqual(["b1"]);
  });

  it("does not show the previous folder's tasks while the new folder attaches", async () => {
    await useWorkflowStore.getState().activate(ROOT_A);
    const attachB = deferred<string>();
    api.attach.mockImplementation(() => attachB.promise);
    const pending = useWorkflowStore.getState().activate(ROOT_B);
    expect(useWorkflowStore.getState().activeRoot).toBeNull();
    attachB.resolve(ROOT_B);
    await pending;
    expect(useWorkflowStore.getState().activeRoot).toBe(ROOT_B);
  });

  it("reloads the lists when switching back to a known folder", async () => {
    await useWorkflowStore.getState().activate(ROOT_A);
    await useWorkflowStore.getState().activate(ROOT_B);
    tasksByRoot[ROOT_A] = [task("a1"), task("a2")];
    await useWorkflowStore.getState().activate(ROOT_A);
    const s = useWorkflowStore.getState();
    expect(s.activeRoot).toBe(ROOT_A);
    expect(s.projects[ROOT_A].tasks.map((t) => t.meta.id)).toEqual(["a1", "a2"]);
  });

  it("activate(null) clears the active root", async () => {
    await useWorkflowStore.getState().activate(ROOT_A);
    await useWorkflowStore.getState().activate(null);
    expect(useWorkflowStore.getState().activeRoot).toBeNull();
  });

  it("ignores task and run events for another root", async () => {
    vi.useFakeTimers();
    await useWorkflowStore.getState().activate(ROOT_A);
    stopBridge = await startWorkflowEventBridge();
    api.listTasks.mockClear();
    handlers.onTaskChanged?.({ projectRoot: ROOT_B, taskId: "b1", rootId: "b1", status: "running" } as TaskChangedEvent);
    handlers.onRunChanged?.({ projectRoot: ROOT_B, rootTaskId: "b1", status: "active" } as RunChangedEvent);
    await vi.advanceTimersByTimeAsync(500);
    expect(api.listTasks).not.toHaveBeenCalled();
    expect(useWorkflowStore.getState().projects[ROOT_B]).toBeUndefined();
  });

  it("debounces task events within 150 ms into one refresh", async () => {
    vi.useFakeTimers();
    await useWorkflowStore.getState().activate(ROOT_A);
    stopBridge = await startWorkflowEventBridge();
    api.listTasks.mockClear();
    handlers.onTaskChanged?.({ projectRoot: ROOT_A, taskId: "a1", rootId: "a1", status: "running" });
    await vi.advanceTimersByTimeAsync(100);
    handlers.onTaskChanged?.({ projectRoot: ROOT_A, taskId: "a1", rootId: "a1", status: "completed" });
    await vi.advanceTimersByTimeAsync(149);
    expect(api.listTasks).not.toHaveBeenCalled();
    await vi.advanceTimersByTimeAsync(1);
    expect(api.listTasks).toHaveBeenCalledTimes(1);
    expect(api.listTasks).toHaveBeenCalledWith(ROOT_A);
  });

  it("updates progress only for known projects", async () => {
    await useWorkflowStore.getState().activate(ROOT_A);
    stopBridge = await startWorkflowEventBridge();
    const base = { attemptId: "at1", kind: "tool" as const };
    handlers.onProgress?.({ ...base, projectRoot: ROOT_A, taskId: "a1", text: "editing" } as ProgressEvent);
    handlers.onProgress?.({ ...base, projectRoot: ROOT_B, taskId: "b1", text: "other" } as ProgressEvent);
    const s = useWorkflowStore.getState();
    expect(s.projects[ROOT_A].progress.a1).toMatchObject({ text: "editing", kind: "tool" });
    expect(s.projects[ROOT_B]).toBeUndefined();
  });

  it("run shows an error dialog for a command error", async () => {
    await useWorkflowStore.getState().activate(ROOT_A);
    const result = await useWorkflowStore
      .getState()
      .run("hold", () => Promise.reject({ code: "WORKFLOW_PROJECT_INVALID", message: "detail" }));
    expect(result).toBeUndefined();
    expect(showMessage).toHaveBeenCalledTimes(1);
    expect(showMessage.mock.calls[0][0]).toContain("detail");
    expect(showMessage.mock.calls[0][1]).toMatchObject({ kind: "error" });
  });

  it("run refreshes silently on TRANSITION_CONFLICT", async () => {
    await useWorkflowStore.getState().activate(ROOT_A);
    api.listTasks.mockClear();
    const result = await useWorkflowStore
      .getState()
      .run("hold", () => Promise.reject({ code: "TRANSITION_CONFLICT", message: "raced" }));
    expect(result).toBeUndefined();
    expect(showMessage).not.toHaveBeenCalled();
    expect(api.listTasks).toHaveBeenCalledWith(ROOT_A);
  });

  it("run returns the result and refreshes after success", async () => {
    await useWorkflowStore.getState().activate(ROOT_A);
    api.listTasks.mockClear();
    const fn = vi.fn(async (root: string) => `done:${root}`);
    const result = await useWorkflowStore.getState().run("hold", fn);
    expect(result).toBe(`done:${ROOT_A}`);
    expect(fn).toHaveBeenCalledWith(ROOT_A);
    expect(api.listTasks).toHaveBeenCalledWith(ROOT_A);
  });

  it("stores a load error on the project", async () => {
    api.listTasks.mockRejectedValue({ code: "WORKFLOW_PROJECT_INVALID", message: "gone" });
    await useWorkflowStore.getState().activate(ROOT_A);
    const p = useWorkflowStore.getState().projects[ROOT_A];
    expect(p.loading).toBe(false);
    expect(p.error).toContain("gone");
  });

  it("openTask and setFilters update the selection and filters", () => {
    useWorkflowStore.getState().openTask("t1");
    useWorkflowStore.getState().setFilters({ view: "matrix", showArchived: true });
    const s = useWorkflowStore.getState();
    expect(s.selectedTaskId).toBe("t1");
    expect(s.filters).toEqual({ workflowId: null, showArchived: true, showCancelled: false, view: "matrix" });
  });
});
