/**
 * TypeScript mirrors of the workflow orchestrator's Tauri command payloads
 * and events (`src-tauri/src/commands/workflow.rs`). Field names are the
 * camelCase serde names of the Rust structs.
 *
 * Command arguments are passed in camelCase (e.g. `projectRoot`, `taskId`).
 * Every project-scoped command rejects a `projectRoot` that is empty, not
 * absolute, or not an existing directory (`WORKFLOW_PROJECT_INVALID`), then
 * attaches the project.
 *
 * Output types (`Workflow`, `Stage`, ...) have every field present;
 * `WorkflowsFileInput` / `WorkflowInput` / `StageInput` may omit fields the
 * backend defaults.
 *
 * Project roots: every event carries the orchestrator's normalized root in
 * `projectRoot` (canonicalized, no trailing separator, no `\\?\` prefix,
 * letter case preserved), which is the value `workflow_attach_project`
 * returns. The UI must compare roots after normalization (on Windows also
 * case-insensitively), never against the raw spelling it passed in.
 */

/** Which coding agent runs a stage. */
export type Provider = "codex" | "copilot" | "opencode" | "claude";

/** A stage's place in the fixed design -> implement -> review pipeline. */
export type Role = "design" | "implement" | "review";

export type IssueTracking = "auto" | "off";

export type TaskStatus =
  | "inbox"
  | "running"
  | "awaiting_user"
  | "attention"
  | "on_hold"
  | "completed"
  | "cancelled";

export type RunStatus =
  | "active"
  | "awaiting_merge"
  | "cancelled"
  | "merged"
  | "discarded";

/**
 * Machine-readable reason a task needs attention; the UI localizes it by
 * `code` (e.g. `ATTENTION_INTERRUPTED`) with `params`. List values are a
 * JSON array string under `items`.
 */
export interface AttentionReason {
  code: string;
  params: Record<string, string>;
}

export type AwaitingKind = "plan_approval" | "question";

/** What an `awaiting_user` task is waiting for. */
export interface AwaitingInfo {
  kind: AwaitingKind;
  /** The agent's question, when `kind` is `question`. */
  question: string | null;
}

export interface HistoryEntry {
  at: string;
  from: TaskStatus | null;
  to: TaskStatus;
  reason: AttentionReason | null;
}

export interface TaskMeta {
  schemaVersion: number;
  id: string;
  title: string;
  status: TaskStatus;
  rootId: string;
  parentId: string | null;
  workflowId: string | null;
  stageId: string | null;
  role: Role | null;
  autoGenerated: boolean;
  archived: boolean;
  createdAt: string;
  updatedAt: string;
  attention: AttentionReason | null;
  history: HistoryEntry[];
  awaiting: AwaitingInfo | null;
  planApproved: boolean;
  userInput: string | null;
  screeningAck: string | null;
  /** The forge Issue tracking this task (root tasks only). */
  issue: IssueRef | null;
  /** Entry kind (`design` | `implement` | `review`) whose Issue comment still awaits sync. */
  pendingIssueEntry: string | null;
}

export interface Task {
  meta: TaskMeta;
  body: string;
}

/** A stage as the backend returns it (every field present). */
export interface Stage {
  id: string;
  role: Role;
  name: string;
  prompt: string;
  completionCriteria: string;
  provider: Provider;
  model: string | null;
  requiresApproval: boolean;
  timeoutMinutes: number;
}

/** A workflow as the backend returns it (every field present). */
export interface Workflow {
  id: string;
  name: string;
  enabled: boolean;
  archived: boolean;
  stages: Stage[];
  reviewReturnTo: Role;
  maxReentryCount: number;
  maxConcurrentRuns: number;
  designDocPath: string | null;
  issueTracking: IssueTracking;
}

/**
 * A stage as sent to the backend: fields with a backend default may be
 * omitted (`model`: null, `requiresApproval`: false, `timeoutMinutes`: 60).
 */
export type StageInput = Omit<Stage, "model" | "requiresApproval" | "timeoutMinutes"> &
  Partial<Pick<Stage, "model" | "requiresApproval" | "timeoutMinutes">>;

/**
 * A workflow as sent to the backend: fields with a backend default may be
 * omitted (`reviewReturnTo`: "design", `maxReentryCount`: 5,
 * `maxConcurrentRuns`: 1, `designDocPath`: null). A `Workflow` is a valid
 * `WorkflowInput`.
 */
export type WorkflowInput = Omit<
  Workflow,
  "stages" | "reviewReturnTo" | "maxReentryCount" | "maxConcurrentRuns" | "designDocPath"
> & {
  stages: StageInput[];
} & Partial<
    Pick<Workflow, "reviewReturnTo" | "maxReentryCount" | "maxConcurrentRuns" | "designDocPath">
  >;

/** Argument of `workflow_save_workflows` (`file`). */
export interface WorkflowsFileInput {
  schemaVersion: number;
  workflows: WorkflowInput[];
}

export interface WorktreeInfo {
  path: string;
  branch: string;
  baseBranch: string;
  baseCommit: string;
}

export type AttemptMode = "single" | "plan" | "execute";

/** How an attempt ended (`AttemptRecord.outcome`). */
export type AttemptOutcome =
  | "completed"
  | "attention"
  | "awaiting_user"
  | "cancelled"
  | "timeout"
  | "failed"
  | "guard_blocked"
  | "output_invalid"
  | "interrupted";

export interface AttemptRecord {
  attemptId: string;
  taskId: string;
  stageId: string;
  sessionId: string;
  /** Reserved; currently always null. */
  runnerPid: number | null;
  startedAt: string;
  finishedAt: string | null;
  outcome: AttemptOutcome | null;
  mode: AttemptMode;
  userInput: string | null;
  /** Entry kind of the Issue entry being posted for this attempt's result (set during the post). */
  issueSyncPending: string | null;
}

export interface FileFingerprint {
  path: string;
  sha256: string | null;
}

export interface PendingTransition {
  fromTaskId: string;
  toStageId: string;
  childTaskId: string;
}

export interface IntegritySnapshot {
  headRef: string;
  headCommit: string;
  baseBranchCommit: string | null;
  gitConfigHash: string;
  hooksHash: string;
  hooksPath: string | null;
}

export interface IntegrityChange {
  code: string;
  detail: string;
}

export interface WorkflowRun {
  schemaVersion: number;
  rootTaskId: string;
  /** Snapshot of the workflow definition at run start. */
  workflow: Workflow;
  status: RunStatus;
  currentTaskId: string;
  reentryCount: number;
  worktree: WorktreeInfo | null;
  attempts: AttemptRecord[];
  pendingTransition: PendingTransition | null;
  integrityBaseline: IntegritySnapshot | null;
  createdAt: string;
  updatedAt: string;
  acknowledgedAgentConfig: FileFingerprint[];
  /** The forge Issue tracking this run (copied from the root task). */
  issue: IssueRef | null;
  /** True once the run's Issue was closed on the forge. */
  issueClosed: boolean;
  /** Error code of the last failed attempt to close the Issue. */
  issueCloseError: string | null;
}

/** A record that could not be loaded while listing. */
export interface StoreWarning {
  file: string;
  /** `STORE_*` code plus detail (not user-facing text). */
  message: string;
}

/** Result of `workflow_list_tasks`. */
export interface TaskList {
  tasks: Task[];
  warnings: StoreWarning[];
}

/** Result of `workflow_list_workflows`. */
export interface WorkflowList {
  workflows: Workflow[];
  warnings: StoreWarning[];
}

/** Result of `workflow_list_runs`. */
export interface RunList {
  runs: WorkflowRun[];
  warnings: StoreWarning[];
}

/** Result of `workflow_task_detail`. */
export interface TaskDetail {
  task: Task;
  run: WorkflowRun | null;
  /** Raw output of the task's latest attempt that has one. */
  latestOutput: string | null;
  /** The last lines of the task's latest attempt log. */
  logTail: string[];
}

export interface CommitSummary {
  hash: string;
  subject: string;
}

/** Result of `workflow_merge_preview`. */
export interface MergePreview {
  branch: string;
  baseBranch: string;
  baseCommit: string;
  /** Branch tip shown by the preview (empty while there are `integrityChanges`); pass it to the merge. */
  headCommit: string;
  commits: CommitSummary[];
  /** The branch diff, capped. */
  diff: string;
  /** Changed paths that need the user's acknowledgement before merging. */
  reviewPaths: string[];
  /**
   * Repository changes since the run's baseline that need acknowledgement.
   * While there are any, `commits`, `diff` and `reviewPaths` are empty.
   */
  integrityChanges: IntegrityChange[];
}

/** One entry of `workflow_probe_providers`. */
export interface ProviderProbe {
  provider: Provider;
  /** The runner's availability report, or `{ kind: "error", detail: <code> }`. */
  result: unknown;
}

/** Result of `workflow_gitignore_status`: workflow paths `.gitignore` does not cover. */
export interface GitignoreStatus {
  missing: string[];
}

export type ForgeKind = "github" | "gitlab";

/** A repository on a forge (`host` may carry a port; `path` has no `.git`). */
export interface ForgeRepo {
  kind: ForgeKind;
  host: string;
  path: string;
}

/** A forge Issue linked to a task, run or intake. */
export interface IssueRef {
  kind: ForgeKind;
  host: string;
  path: string;
  number: number;
  url: string;
}

/** Result of `workflow_forge_probe`: whether Issues can be tracked for the project. */
export interface ForgeProbe {
  /** The forge repository of `origin`, if it points at one. */
  repo: ForgeRepo | null;
  /** The detected forge's CLI is installed (with no repo: either CLI is). */
  cliAvailable: boolean;
  /** The detected forge's CLI is logged in to its host. */
  authenticated: boolean;
}

/** A draft or committed attachment's metadata. */
export interface AttachmentMeta {
  schemaVersion: number;
  id: string;
  originalName: string;
  /** Sanitized file name the content is stored under. */
  storedName: string;
  mime: string;
  size: number;
  sha256: string;
  createdAt: string;
}

export type IntakeKind = "feature" | "bug";

export type IntakeStatus = "active" | "finalizing" | "done" | "abandoned";

/** The last completed step of the resumable finalize pipeline. */
export type FinalizeStage = "ready" | "issue_created" | "attachments_committed" | "task_created" | "done";

export type IntakeMessageRole = "user" | "assistant" | "error";

export interface IntakeMessage {
  id: string;
  role: IntakeMessageRole;
  /** For `error` messages: the failure code (e.g. `INTAKE_TURN_TIMEOUT`). */
  text: string;
  /** Draft attachments sent with this message. */
  draftIds: string[];
  at: string;
  /**
   * For `error` messages, debugging detail shown with the code: the agent's
   * raw reply (at most 16 KiB) when it broke the output contract.
   */
  detail: string | null;
}

export interface IntakeQuestion {
  text: string;
  options: string[];
}

export interface IntakeProposal {
  title: string;
  body: string;
}

export type DocUpdateStatus = "pending" | "applied" | "rejected";

/** A proposed replacement of a project document's content. */
export interface DocUpdateProposal {
  id: string;
  /** Project-relative path of the document. */
  path: string;
  content: string;
  status: DocUpdateStatus;
  /** Why the update was rejected when proposed (an `INTAKE_*` code). */
  reason: string | null;
  /**
   * sha256 of the document when the update was proposed (`null`: it did not
   * exist). Applying is refused with `INTAKE_DOC_CHANGED_SINCE_PROPOSAL` when
   * the document no longer matches.
   */
  baseSha256: string | null;
}

export interface FinalizeState {
  stage: FinalizeStage;
  rootTaskId: string | null;
  issue: IssueRef | null;
  attachmentIds: string[];
  skipIssue: boolean;
  /** The Issue may have been created before a crash; a retry looks it up first. */
  issueCreating: boolean;
  /** Error code of the last failed finalize step. */
  lastError: string | null;
}

/** An intake session (`.mdium/intakes/<intakeId>.json`). */
export interface IntakeSession {
  schemaVersion: number;
  id: string;
  workflowId: string;
  kind: IntakeKind;
  provider: Provider;
  model: string | null;
  status: IntakeStatus;
  messages: IntakeMessage[];
  lastQuestion: IntakeQuestion | null;
  proposal: IntakeProposal | null;
  docUpdates: DocUpdateProposal[];
  finalize: FinalizeState;
  createdAt: string;
  updatedAt: string;
}

/** An intake session as the intake commands return it. */
export interface IntakeSessionView extends IntakeSession {
  /** An agent turn of the session is running. */
  busy: boolean;
  /** A finalize of the session is running (its actions are unavailable meanwhile). */
  finalizeRunning: boolean;
  /** Paths of the applied doc updates: files written into the working tree that still need committing. */
  appliedDocPaths: string[];
}

/** Result of `workflow_intake_list`: sessions newest first. */
export interface IntakeList {
  sessions: IntakeSessionView[];
  warnings: StoreWarning[];
}

/** Rejection value of every workflow command. `message` is a log detail; localize by `code`. */
export interface CommandError {
  code: string;
  message: string;
}

/** Event names emitted by the orchestrator. */
export const WORKFLOW_TASK_CHANGED_EVENT = "workflow://task-changed";
export const WORKFLOW_RUN_CHANGED_EVENT = "workflow://run-changed";
export const WORKFLOW_PROGRESS_EVENT = "workflow://progress";
export const WORKFLOW_INTAKE_CHANGED_EVENT = "workflow://intake-changed";
export const WORKFLOW_WORKFLOWS_CHANGED_EVENT = "workflow://workflows-changed";

/** Payload of `workflow://task-changed`. `projectRoot` is the normalized root. */
export interface TaskChangedEvent {
  projectRoot: string;
  taskId: string;
  rootId: string;
  status: TaskStatus;
}

/** Payload of `workflow://run-changed`. `projectRoot` is the normalized root. */
export interface RunChangedEvent {
  projectRoot: string;
  rootTaskId: string;
  status: RunStatus;
}

/**
 * Payload of `workflow://progress` (at most 4 per second per attempt;
 * `text` at most 500 chars). `projectRoot` is the normalized root.
 */
export interface ProgressEvent {
  projectRoot: string;
  taskId: string;
  attemptId: string;
  kind: "message" | "tool";
  text: string;
}

/**
 * Payload of `workflow://intake-changed`: emitted on every session change
 * and when an agent turn starts or ends. `projectRoot` is the normalized root.
 */
export interface IntakeChangedEvent {
  projectRoot: string;
  intakeId: string;
  status: IntakeStatus;
  /** An agent turn of the session is running. */
  busy: boolean;
}

/** Payload of `workflow://workflows-changed` (`workflows.json` was rewritten). */
export interface WorkflowsChangedEvent {
  projectRoot: string;
}

/**
 * Sent by an intake window to the main window (`emitTo("main", …)`) after
 * finalizing: open the created task. `projectRoot` is the normalized root.
 * The main window answers with `workflow://open-task-ack`.
 */
export const WORKFLOW_OPEN_TASK_EVENT = "workflow://open-task";

/** Payload of `workflow://open-task`. */
export interface OpenTaskEvent {
  projectRoot: string;
  taskId: string;
  /** Label of the sending intake window (the acknowledgement goes there). */
  sender: string;
}

/**
 * Sent by the main window to the intake window that sent
 * `workflow://open-task` (`emitTo(sender, …)`).
 */
export const WORKFLOW_OPEN_TASK_ACK_EVENT = "workflow://open-task-ack";

/** Payload of `workflow://open-task-ack`. */
export interface OpenTaskAck {
  taskId: string;
  /** The task's project is open in the main window and the task is shown. */
  handled: boolean;
}
