/**
 * TypeScript mirrors of the workflow orchestrator's Tauri command payloads
 * and events (`src-tauri/src/commands/workflow.rs`). Field names are the
 * camelCase serde names of the Rust structs.
 *
 * Command arguments are passed in camelCase (e.g. `projectRoot`, `taskId`).
 * Every project-scoped command rejects a `projectRoot` that is empty, not
 * absolute, or not an existing directory (`WORKFLOW_PROJECT_INVALID`), then
 * attaches the project.
 *
 * Output types (`Workflow`, `Stage`, ...) have every field present;
 * `WorkflowsFileInput` / `WorkflowInput` / `StageInput` may omit fields the
 * backend defaults.
 *
 * Project roots: every event carries the orchestrator's normalized root in
 * `projectRoot` (canonicalized, no trailing separator, no `\\?\` prefix,
 * letter case preserved), which is the value `workflow_attach_project`
 * returns. The UI must compare roots after normalization (on Windows also
 * case-insensitively), never against the raw spelling it passed in.
 */

/** Which coding agent runs a stage. */
export type Provider = "codex" | "copilot" | "opencode" | "claude";

/** A stage's place in the fixed design -> implement -> review pipeline. */
export type Role = "design" | "implement" | "review";

export type IssueTracking = "auto" | "off";

export type TaskStatus =
  | "inbox"
  | "running"
  | "awaiting_user"
  | "attention"
  | "on_hold"
  | "completed"
  | "cancelled";

export type RunStatus =
  | "active"
  | "awaiting_merge"
  | "cancelled"
  | "merged"
  | "discarded";

/**
 * Machine-readable reason a task needs attention; the UI localizes it by
 * `code` (e.g. `ATTENTION_INTERRUPTED`) with `params`. List values are a
 * JSON array string under `items`.
 */
export interface AttentionReason {
  code: string;
  params: Record<string, string>;
}

export type AwaitingKind = "plan_approval" | "question";

/** What an `awaiting_user` task is waiting for. */
export interface AwaitingInfo {
  kind: AwaitingKind;
  /** The agent's question, when `kind` is `question`. */
  question: string | null;
}

export interface HistoryEntry {
  at: string;
  from: TaskStatus | null;
  to: TaskStatus;
  reason: AttentionReason | null;
}

export interface TaskMeta {
  schemaVersion: number;
  id: string;
  title: string;
  status: TaskStatus;
  rootId: string;
  parentId: string | null;
  workflowId: string | null;
  stageId: string | null;
  role: Role | null;
  autoGenerated: boolean;
  archived: boolean;
  createdAt: string;
  updatedAt: string;
  attention: AttentionReason | null;
  history: HistoryEntry[];
  awaiting: AwaitingInfo | null;
  planApproved: boolean;
  userInput: string | null;
  screeningAck: string | null;
}

export interface Task {
  meta: TaskMeta;
  body: string;
}

/** A stage as the backend returns it (every field present). */
export interface Stage {
  id: string;
  role: Role;
  name: string;
  prompt: string;
  completionCriteria: string;
  provider: Provider;
  model: string | null;
  requiresApproval: boolean;
  timeoutMinutes: number;
}

/** A workflow as the backend returns it (every field present). */
export interface Workflow {
  id: string;
  name: string;
  enabled: boolean;
  archived: boolean;
  stages: Stage[];
  reviewReturnTo: Role;
  maxReentryCount: number;
  maxConcurrentRuns: number;
  designDocPath: string | null;
  issueTracking: IssueTracking;
}

/**
 * A stage as sent to the backend: fields with a backend default may be
 * omitted (`model`: null, `requiresApproval`: false, `timeoutMinutes`: 60).
 */
export type StageInput = Omit<Stage, "model" | "requiresApproval" | "timeoutMinutes"> &
  Partial<Pick<Stage, "model" | "requiresApproval" | "timeoutMinutes">>;

/**
 * A workflow as sent to the backend: fields with a backend default may be
 * omitted (`reviewReturnTo`: "design", `maxReentryCount`: 5,
 * `maxConcurrentRuns`: 1, `designDocPath`: null). A `Workflow` is a valid
 * `WorkflowInput`.
 */
export type WorkflowInput = Omit<
  Workflow,
  "stages" | "reviewReturnTo" | "maxReentryCount" | "maxConcurrentRuns" | "designDocPath"
> & {
  stages: StageInput[];
} & Partial<
    Pick<Workflow, "reviewReturnTo" | "maxReentryCount" | "maxConcurrentRuns" | "designDocPath">
  >;

/** Argument of `workflow_save_workflows` (`file`). */
export interface WorkflowsFileInput {
  schemaVersion: number;
  workflows: WorkflowInput[];
}

export interface WorktreeInfo {
  path: string;
  branch: string;
  baseBranch: string;
  baseCommit: string;
}

export type AttemptMode = "single" | "plan" | "execute";

/** How an attempt ended (`AttemptRecord.outcome`). */
export type AttemptOutcome =
  | "completed"
  | "attention"
  | "awaiting_user"
  | "cancelled"
  | "timeout"
  | "failed"
  | "guard_blocked"
  | "output_invalid"
  | "interrupted";

export interface AttemptRecord {
  attemptId: string;
  taskId: string;
  stageId: string;
  sessionId: string;
  /** Reserved; currently always null. */
  runnerPid: number | null;
  startedAt: string;
  finishedAt: string | null;
  outcome: AttemptOutcome | null;
  mode: AttemptMode;
  userInput: string | null;
}

export interface FileFingerprint {
  path: string;
  sha256: string | null;
}

export interface PendingTransition {
  fromTaskId: string;
  toStageId: string;
  childTaskId: string;
}

export interface IntegritySnapshot {
  headRef: string;
  headCommit: string;
  baseBranchCommit: string | null;
  gitConfigHash: string;
  hooksHash: string;
  hooksPath: string | null;
}

export interface IntegrityChange {
  code: string;
  detail: string;
}

export interface WorkflowRun {
  schemaVersion: number;
  rootTaskId: string;
  /** Snapshot of the workflow definition at run start. */
  workflow: Workflow;
  status: RunStatus;
  currentTaskId: string;
  reentryCount: number;
  worktree: WorktreeInfo | null;
  attempts: AttemptRecord[];
  pendingTransition: PendingTransition | null;
  integrityBaseline: IntegritySnapshot | null;
  createdAt: string;
  updatedAt: string;
  acknowledgedAgentConfig: FileFingerprint[];
}

/** A record that could not be loaded while listing. */
export interface StoreWarning {
  file: string;
  /** `STORE_*` code plus detail (not user-facing text). */
  message: string;
}

/** Result of `workflow_list_tasks`. */
export interface TaskList {
  tasks: Task[];
  warnings: StoreWarning[];
}

/** Result of `workflow_list_workflows`. */
export interface WorkflowList {
  workflows: Workflow[];
  warnings: StoreWarning[];
}

/** Result of `workflow_list_runs`. */
export interface RunList {
  runs: WorkflowRun[];
  warnings: StoreWarning[];
}

/** Result of `workflow_task_detail`. */
export interface TaskDetail {
  task: Task;
  run: WorkflowRun | null;
  /** Raw output of the task's latest attempt that has one. */
  latestOutput: string | null;
  /** The last lines of the task's latest attempt log. */
  logTail: string[];
}

export interface CommitSummary {
  hash: string;
  subject: string;
}

/** Result of `workflow_merge_preview`. */
export interface MergePreview {
  branch: string;
  baseBranch: string;
  baseCommit: string;
  commits: CommitSummary[];
  /** The branch diff, capped. */
  diff: string;
  /** Changed paths that need the user's acknowledgement before merging. */
  reviewPaths: string[];
  /**
   * Repository changes since the run's baseline that need acknowledgement.
   * While there are any, `commits`, `diff` and `reviewPaths` are empty.
   */
  integrityChanges: IntegrityChange[];
}

/** One entry of `workflow_probe_providers`. */
export interface ProviderProbe {
  provider: Provider;
  /** The runner's availability report, or `{ kind: "error", detail: <code> }`. */
  result: unknown;
}

/** Result of `workflow_gitignore_status`: workflow paths `.gitignore` does not cover. */
export interface GitignoreStatus {
  missing: string[];
}

/** Rejection value of every workflow command. `message` is a log detail; localize by `code`. */
export interface CommandError {
  code: string;
  message: string;
}

/** Event names emitted by the orchestrator. */
export const WORKFLOW_TASK_CHANGED_EVENT = "workflow://task-changed";
export const WORKFLOW_RUN_CHANGED_EVENT = "workflow://run-changed";
export const WORKFLOW_PROGRESS_EVENT = "workflow://progress";

/** Payload of `workflow://task-changed`. `projectRoot` is the normalized root. */
export interface TaskChangedEvent {
  projectRoot: string;
  taskId: string;
  rootId: string;
  status: TaskStatus;
}

/** Payload of `workflow://run-changed`. `projectRoot` is the normalized root. */
export interface RunChangedEvent {
  projectRoot: string;
  rootTaskId: string;
  status: RunStatus;
}

/**
 * Payload of `workflow://progress` (at most 4 per second per attempt;
 * `text` at most 500 chars). `projectRoot` is the normalized root.
 */
export interface ProgressEvent {
  projectRoot: string;
  taskId: string;
  attemptId: string;
  kind: "message" | "tool";
  text: string;
}
